begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|// Copyright (C) 2013 The Android Open Source Project
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// Licensed under the Apache License, Version 2.0 (the "License");
end_comment

begin_comment
comment|// you may not use this file except in compliance with the License.
end_comment

begin_comment
comment|// You may obtain a copy of the License at
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// http://www.apache.org/licenses/LICENSE-2.0
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// Unless required by applicable law or agreed to in writing, software
end_comment

begin_comment
comment|// distributed under the License is distributed on an "AS IS" BASIS,
end_comment

begin_comment
comment|// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
end_comment

begin_comment
comment|// See the License for the specific language governing permissions and
end_comment

begin_comment
comment|// limitations under the License.
end_comment

begin_package
DECL|package|com.google.gerrit.server.change
package|package
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|change
package|;
end_package

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Preconditions
operator|.
name|checkState
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableList
operator|.
name|toImmutableList
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableSet
operator|.
name|toImmutableSet
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|entities
operator|.
name|Change
operator|.
name|INITIAL_PATCH_SET_ID
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|change
operator|.
name|ReviewerAdder
operator|.
name|newAddReviewerInputFromCommitIdentity
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|notedb
operator|.
name|ReviewerStateInternal
operator|.
name|REVIEWER
import|;
end_import

begin_import
import|import static
name|java
operator|.
name|util
operator|.
name|Objects
operator|.
name|requireNonNull
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|MoreObjects
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableList
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|Iterables
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|Streams
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|flogger
operator|.
name|FluentLogger
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|common
operator|.
name|FooterConstants
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|common
operator|.
name|data
operator|.
name|LabelType
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|common
operator|.
name|data
operator|.
name|LabelTypes
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|entities
operator|.
name|Account
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|entities
operator|.
name|BranchNameKey
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|entities
operator|.
name|Change
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|entities
operator|.
name|ChangeMessage
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|entities
operator|.
name|PatchSet
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|entities
operator|.
name|PatchSetApproval
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|entities
operator|.
name|PatchSetInfo
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|entities
operator|.
name|SubmissionId
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|api
operator|.
name|changes
operator|.
name|NotifyHandling
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|ReviewerState
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|restapi
operator|.
name|ResourceConflictException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|restapi
operator|.
name|RestApiException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|restapi
operator|.
name|UnprocessableEntityException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|ApprovalsUtil
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|ChangeMessagesUtil
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|PatchSetUtil
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|change
operator|.
name|ReviewerAdder
operator|.
name|InternalAddReviewerInput
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|change
operator|.
name|ReviewerAdder
operator|.
name|ReviewerAddition
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|change
operator|.
name|ReviewerAdder
operator|.
name|ReviewerAdditionList
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|config
operator|.
name|SendEmailExecutor
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|events
operator|.
name|CommitReceivedEvent
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|extensions
operator|.
name|events
operator|.
name|CommentAdded
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|extensions
operator|.
name|events
operator|.
name|RevisionCreated
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|git
operator|.
name|GroupCollector
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|git
operator|.
name|validators
operator|.
name|CommitValidationException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|git
operator|.
name|validators
operator|.
name|CommitValidators
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|mail
operator|.
name|send
operator|.
name|CreateChangeSender
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|notedb
operator|.
name|ChangeUpdate
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|patch
operator|.
name|PatchSetInfoFactory
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|permissions
operator|.
name|PermissionBackend
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|permissions
operator|.
name|PermissionBackendException
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|project
operator|.
name|ProjectCache
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|project
operator|.
name|ProjectState
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|ssh
operator|.
name|NoSshInfo
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|update
operator|.
name|ChangeContext
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|update
operator|.
name|Context
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|update
operator|.
name|InsertChangeOp
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|update
operator|.
name|RepoContext
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|util
operator|.
name|RequestScopePropagator
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|inject
operator|.
name|Inject
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|inject
operator|.
name|assistedinject
operator|.
name|Assisted
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Optional
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|ExecutorService
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|concurrent
operator|.
name|Future
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jgit
operator|.
name|errors
operator|.
name|ConfigInvalidException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jgit
operator|.
name|lib
operator|.
name|ObjectId
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jgit
operator|.
name|revwalk
operator|.
name|RevCommit
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jgit
operator|.
name|revwalk
operator|.
name|RevWalk
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jgit
operator|.
name|transport
operator|.
name|ReceiveCommand
import|;
end_import

begin_class
DECL|class|ChangeInserter
specifier|public
class|class
name|ChangeInserter
implements|implements
name|InsertChangeOp
block|{
DECL|field|logger
specifier|private
specifier|static
specifier|final
name|FluentLogger
name|logger
init|=
name|FluentLogger
operator|.
name|forEnclosingClass
argument_list|()
decl_stmt|;
DECL|interface|Factory
specifier|public
interface|interface
name|Factory
block|{
DECL|method|create (Change.Id cid, ObjectId commitId, String refName)
name|ChangeInserter
name|create
parameter_list|(
name|Change
operator|.
name|Id
name|cid
parameter_list|,
name|ObjectId
name|commitId
parameter_list|,
name|String
name|refName
parameter_list|)
function_decl|;
block|}
DECL|field|permissionBackend
specifier|private
specifier|final
name|PermissionBackend
name|permissionBackend
decl_stmt|;
DECL|field|projectCache
specifier|private
specifier|final
name|ProjectCache
name|projectCache
decl_stmt|;
DECL|field|patchSetInfoFactory
specifier|private
specifier|final
name|PatchSetInfoFactory
name|patchSetInfoFactory
decl_stmt|;
DECL|field|psUtil
specifier|private
specifier|final
name|PatchSetUtil
name|psUtil
decl_stmt|;
DECL|field|approvalsUtil
specifier|private
specifier|final
name|ApprovalsUtil
name|approvalsUtil
decl_stmt|;
DECL|field|cmUtil
specifier|private
specifier|final
name|ChangeMessagesUtil
name|cmUtil
decl_stmt|;
DECL|field|createChangeSenderFactory
specifier|private
specifier|final
name|CreateChangeSender
operator|.
name|Factory
name|createChangeSenderFactory
decl_stmt|;
DECL|field|sendEmailExecutor
specifier|private
specifier|final
name|ExecutorService
name|sendEmailExecutor
decl_stmt|;
DECL|field|commitValidatorsFactory
specifier|private
specifier|final
name|CommitValidators
operator|.
name|Factory
name|commitValidatorsFactory
decl_stmt|;
DECL|field|revisionCreated
specifier|private
specifier|final
name|RevisionCreated
name|revisionCreated
decl_stmt|;
DECL|field|commentAdded
specifier|private
specifier|final
name|CommentAdded
name|commentAdded
decl_stmt|;
DECL|field|reviewerAdder
specifier|private
specifier|final
name|ReviewerAdder
name|reviewerAdder
decl_stmt|;
DECL|field|changeId
specifier|private
specifier|final
name|Change
operator|.
name|Id
name|changeId
decl_stmt|;
DECL|field|psId
specifier|private
specifier|final
name|PatchSet
operator|.
name|Id
name|psId
decl_stmt|;
DECL|field|commitId
specifier|private
specifier|final
name|ObjectId
name|commitId
decl_stmt|;
DECL|field|refName
specifier|private
specifier|final
name|String
name|refName
decl_stmt|;
comment|// Fields exposed as setters.
DECL|field|status
specifier|private
name|Change
operator|.
name|Status
name|status
decl_stmt|;
DECL|field|topic
specifier|private
name|String
name|topic
decl_stmt|;
DECL|field|message
specifier|private
name|String
name|message
decl_stmt|;
DECL|field|patchSetDescription
specifier|private
name|String
name|patchSetDescription
decl_stmt|;
DECL|field|isPrivate
specifier|private
name|boolean
name|isPrivate
decl_stmt|;
DECL|field|workInProgress
specifier|private
name|boolean
name|workInProgress
decl_stmt|;
DECL|field|groups
specifier|private
name|List
argument_list|<
name|String
argument_list|>
name|groups
init|=
name|Collections
operator|.
name|emptyList
argument_list|()
decl_stmt|;
DECL|field|validate
specifier|private
name|boolean
name|validate
init|=
literal|true
decl_stmt|;
DECL|field|approvals
specifier|private
name|Map
argument_list|<
name|String
argument_list|,
name|Short
argument_list|>
name|approvals
decl_stmt|;
DECL|field|requestScopePropagator
specifier|private
name|RequestScopePropagator
name|requestScopePropagator
decl_stmt|;
DECL|field|fireRevisionCreated
specifier|private
name|boolean
name|fireRevisionCreated
decl_stmt|;
DECL|field|sendMail
specifier|private
name|boolean
name|sendMail
decl_stmt|;
DECL|field|updateRef
specifier|private
name|boolean
name|updateRef
decl_stmt|;
DECL|field|revertOf
specifier|private
name|Change
operator|.
name|Id
name|revertOf
decl_stmt|;
DECL|field|reviewerInputs
specifier|private
name|ImmutableList
argument_list|<
name|InternalAddReviewerInput
argument_list|>
name|reviewerInputs
decl_stmt|;
comment|// Fields set during the insertion process.
DECL|field|cmd
specifier|private
name|ReceiveCommand
name|cmd
decl_stmt|;
DECL|field|change
specifier|private
name|Change
name|change
decl_stmt|;
DECL|field|changeMessage
specifier|private
name|ChangeMessage
name|changeMessage
decl_stmt|;
DECL|field|patchSetInfo
specifier|private
name|PatchSetInfo
name|patchSetInfo
decl_stmt|;
DECL|field|patchSet
specifier|private
name|PatchSet
name|patchSet
decl_stmt|;
DECL|field|pushCert
specifier|private
name|String
name|pushCert
decl_stmt|;
DECL|field|projectState
specifier|private
name|ProjectState
name|projectState
decl_stmt|;
DECL|field|reviewerAdditions
specifier|private
name|ReviewerAdditionList
name|reviewerAdditions
decl_stmt|;
annotation|@
name|Inject
DECL|method|ChangeInserter ( PermissionBackend permissionBackend, ProjectCache projectCache, PatchSetInfoFactory patchSetInfoFactory, PatchSetUtil psUtil, ApprovalsUtil approvalsUtil, ChangeMessagesUtil cmUtil, CreateChangeSender.Factory createChangeSenderFactory, @SendEmailExecutor ExecutorService sendEmailExecutor, CommitValidators.Factory commitValidatorsFactory, CommentAdded commentAdded, RevisionCreated revisionCreated, ReviewerAdder reviewerAdder, @Assisted Change.Id changeId, @Assisted ObjectId commitId, @Assisted String refName)
name|ChangeInserter
parameter_list|(
name|PermissionBackend
name|permissionBackend
parameter_list|,
name|ProjectCache
name|projectCache
parameter_list|,
name|PatchSetInfoFactory
name|patchSetInfoFactory
parameter_list|,
name|PatchSetUtil
name|psUtil
parameter_list|,
name|ApprovalsUtil
name|approvalsUtil
parameter_list|,
name|ChangeMessagesUtil
name|cmUtil
parameter_list|,
name|CreateChangeSender
operator|.
name|Factory
name|createChangeSenderFactory
parameter_list|,
annotation|@
name|SendEmailExecutor
name|ExecutorService
name|sendEmailExecutor
parameter_list|,
name|CommitValidators
operator|.
name|Factory
name|commitValidatorsFactory
parameter_list|,
name|CommentAdded
name|commentAdded
parameter_list|,
name|RevisionCreated
name|revisionCreated
parameter_list|,
name|ReviewerAdder
name|reviewerAdder
parameter_list|,
annotation|@
name|Assisted
name|Change
operator|.
name|Id
name|changeId
parameter_list|,
annotation|@
name|Assisted
name|ObjectId
name|commitId
parameter_list|,
annotation|@
name|Assisted
name|String
name|refName
parameter_list|)
block|{
name|this
operator|.
name|permissionBackend
operator|=
name|permissionBackend
expr_stmt|;
name|this
operator|.
name|projectCache
operator|=
name|projectCache
expr_stmt|;
name|this
operator|.
name|patchSetInfoFactory
operator|=
name|patchSetInfoFactory
expr_stmt|;
name|this
operator|.
name|psUtil
operator|=
name|psUtil
expr_stmt|;
name|this
operator|.
name|approvalsUtil
operator|=
name|approvalsUtil
expr_stmt|;
name|this
operator|.
name|cmUtil
operator|=
name|cmUtil
expr_stmt|;
name|this
operator|.
name|createChangeSenderFactory
operator|=
name|createChangeSenderFactory
expr_stmt|;
name|this
operator|.
name|sendEmailExecutor
operator|=
name|sendEmailExecutor
expr_stmt|;
name|this
operator|.
name|commitValidatorsFactory
operator|=
name|commitValidatorsFactory
expr_stmt|;
name|this
operator|.
name|revisionCreated
operator|=
name|revisionCreated
expr_stmt|;
name|this
operator|.
name|commentAdded
operator|=
name|commentAdded
expr_stmt|;
name|this
operator|.
name|reviewerAdder
operator|=
name|reviewerAdder
expr_stmt|;
name|this
operator|.
name|changeId
operator|=
name|changeId
expr_stmt|;
name|this
operator|.
name|psId
operator|=
name|PatchSet
operator|.
name|id
argument_list|(
name|changeId
argument_list|,
name|INITIAL_PATCH_SET_ID
argument_list|)
expr_stmt|;
name|this
operator|.
name|commitId
operator|=
name|commitId
operator|.
name|copy
argument_list|()
expr_stmt|;
name|this
operator|.
name|refName
operator|=
name|refName
expr_stmt|;
name|this
operator|.
name|reviewerInputs
operator|=
name|ImmutableList
operator|.
name|of
argument_list|()
expr_stmt|;
name|this
operator|.
name|approvals
operator|=
name|Collections
operator|.
name|emptyMap
argument_list|()
expr_stmt|;
name|this
operator|.
name|fireRevisionCreated
operator|=
literal|true
expr_stmt|;
name|this
operator|.
name|sendMail
operator|=
literal|true
expr_stmt|;
name|this
operator|.
name|updateRef
operator|=
literal|true
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|createChange (Context ctx)
specifier|public
name|Change
name|createChange
parameter_list|(
name|Context
name|ctx
parameter_list|)
throws|throws
name|IOException
block|{
name|change
operator|=
operator|new
name|Change
argument_list|(
name|getChangeKey
argument_list|(
name|ctx
operator|.
name|getRevWalk
argument_list|()
argument_list|,
name|commitId
argument_list|)
argument_list|,
name|changeId
argument_list|,
name|ctx
operator|.
name|getAccountId
argument_list|()
argument_list|,
name|BranchNameKey
operator|.
name|create
argument_list|(
name|ctx
operator|.
name|getProject
argument_list|()
argument_list|,
name|refName
argument_list|)
argument_list|,
name|ctx
operator|.
name|getWhen
argument_list|()
argument_list|)
expr_stmt|;
name|change
operator|.
name|setStatus
argument_list|(
name|MoreObjects
operator|.
name|firstNonNull
argument_list|(
name|status
argument_list|,
name|Change
operator|.
name|Status
operator|.
name|NEW
argument_list|)
argument_list|)
expr_stmt|;
name|change
operator|.
name|setTopic
argument_list|(
name|topic
argument_list|)
expr_stmt|;
name|change
operator|.
name|setPrivate
argument_list|(
name|isPrivate
argument_list|)
expr_stmt|;
name|change
operator|.
name|setWorkInProgress
argument_list|(
name|workInProgress
argument_list|)
expr_stmt|;
name|change
operator|.
name|setReviewStarted
argument_list|(
operator|!
name|workInProgress
argument_list|)
expr_stmt|;
name|change
operator|.
name|setRevertOf
argument_list|(
name|revertOf
argument_list|)
expr_stmt|;
return|return
name|change
return|;
block|}
DECL|method|getChangeKey (RevWalk rw, ObjectId id)
specifier|private
specifier|static
name|Change
operator|.
name|Key
name|getChangeKey
parameter_list|(
name|RevWalk
name|rw
parameter_list|,
name|ObjectId
name|id
parameter_list|)
throws|throws
name|IOException
block|{
name|RevCommit
name|commit
init|=
name|rw
operator|.
name|parseCommit
argument_list|(
name|id
argument_list|)
decl_stmt|;
name|rw
operator|.
name|parseBody
argument_list|(
name|commit
argument_list|)
expr_stmt|;
name|List
argument_list|<
name|String
argument_list|>
name|idList
init|=
name|commit
operator|.
name|getFooterLines
argument_list|(
name|FooterConstants
operator|.
name|CHANGE_ID
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|idList
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
return|return
name|Change
operator|.
name|key
argument_list|(
name|idList
operator|.
name|get
argument_list|(
name|idList
operator|.
name|size
argument_list|()
operator|-
literal|1
argument_list|)
operator|.
name|trim
argument_list|()
argument_list|)
return|;
block|}
comment|// A Change-Id is generated for the review, but not appended to the commit message.
comment|// This can happen if requireChangeId is false.
return|return
name|Change
operator|.
name|generateKey
argument_list|()
return|;
block|}
DECL|method|getPatchSetId ()
specifier|public
name|PatchSet
operator|.
name|Id
name|getPatchSetId
parameter_list|()
block|{
return|return
name|psId
return|;
block|}
DECL|method|getCommitId ()
specifier|public
name|ObjectId
name|getCommitId
parameter_list|()
block|{
return|return
name|commitId
return|;
block|}
DECL|method|getChange ()
specifier|public
name|Change
name|getChange
parameter_list|()
block|{
name|checkState
argument_list|(
name|change
operator|!=
literal|null
argument_list|,
literal|"getChange() only valid after creating change"
argument_list|)
expr_stmt|;
return|return
name|change
return|;
block|}
DECL|method|setTopic (String topic)
specifier|public
name|ChangeInserter
name|setTopic
parameter_list|(
name|String
name|topic
parameter_list|)
block|{
name|checkState
argument_list|(
name|change
operator|==
literal|null
argument_list|,
literal|"setTopic(String) only valid before creating change"
argument_list|)
expr_stmt|;
name|this
operator|.
name|topic
operator|=
name|topic
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setMessage (String message)
specifier|public
name|ChangeInserter
name|setMessage
parameter_list|(
name|String
name|message
parameter_list|)
block|{
name|this
operator|.
name|message
operator|=
name|message
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setPatchSetDescription (String patchSetDescription)
specifier|public
name|ChangeInserter
name|setPatchSetDescription
parameter_list|(
name|String
name|patchSetDescription
parameter_list|)
block|{
name|this
operator|.
name|patchSetDescription
operator|=
name|patchSetDescription
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setValidate (boolean validate)
specifier|public
name|ChangeInserter
name|setValidate
parameter_list|(
name|boolean
name|validate
parameter_list|)
block|{
name|this
operator|.
name|validate
operator|=
name|validate
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setReviewersAndCcs ( Iterable<Account.Id> reviewers, Iterable<Account.Id> ccs)
specifier|public
name|ChangeInserter
name|setReviewersAndCcs
parameter_list|(
name|Iterable
argument_list|<
name|Account
operator|.
name|Id
argument_list|>
name|reviewers
parameter_list|,
name|Iterable
argument_list|<
name|Account
operator|.
name|Id
argument_list|>
name|ccs
parameter_list|)
block|{
return|return
name|setReviewersAndCcsAsStrings
argument_list|(
name|Iterables
operator|.
name|transform
argument_list|(
name|reviewers
argument_list|,
name|Account
operator|.
name|Id
operator|::
name|toString
argument_list|)
argument_list|,
name|Iterables
operator|.
name|transform
argument_list|(
name|ccs
argument_list|,
name|Account
operator|.
name|Id
operator|::
name|toString
argument_list|)
argument_list|)
return|;
block|}
DECL|method|setReviewersAndCcsAsStrings ( Iterable<String> reviewers, Iterable<String> ccs)
specifier|public
name|ChangeInserter
name|setReviewersAndCcsAsStrings
parameter_list|(
name|Iterable
argument_list|<
name|String
argument_list|>
name|reviewers
parameter_list|,
name|Iterable
argument_list|<
name|String
argument_list|>
name|ccs
parameter_list|)
block|{
name|reviewerInputs
operator|=
name|Streams
operator|.
name|concat
argument_list|(
name|Streams
operator|.
name|stream
argument_list|(
name|reviewers
argument_list|)
operator|.
name|distinct
argument_list|()
operator|.
name|map
argument_list|(
name|id
lambda|->
name|newAddReviewerInput
argument_list|(
name|id
argument_list|,
name|ReviewerState
operator|.
name|REVIEWER
argument_list|)
argument_list|)
argument_list|,
name|Streams
operator|.
name|stream
argument_list|(
name|ccs
argument_list|)
operator|.
name|distinct
argument_list|()
operator|.
name|map
argument_list|(
name|id
lambda|->
name|newAddReviewerInput
argument_list|(
name|id
argument_list|,
name|ReviewerState
operator|.
name|CC
argument_list|)
argument_list|)
argument_list|)
operator|.
name|collect
argument_list|(
name|toImmutableList
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setPrivate (boolean isPrivate)
specifier|public
name|ChangeInserter
name|setPrivate
parameter_list|(
name|boolean
name|isPrivate
parameter_list|)
block|{
name|checkState
argument_list|(
name|change
operator|==
literal|null
argument_list|,
literal|"setPrivate(boolean) only valid before creating change"
argument_list|)
expr_stmt|;
name|this
operator|.
name|isPrivate
operator|=
name|isPrivate
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setWorkInProgress (boolean workInProgress)
specifier|public
name|ChangeInserter
name|setWorkInProgress
parameter_list|(
name|boolean
name|workInProgress
parameter_list|)
block|{
name|this
operator|.
name|workInProgress
operator|=
name|workInProgress
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setStatus (Change.Status status)
specifier|public
name|ChangeInserter
name|setStatus
parameter_list|(
name|Change
operator|.
name|Status
name|status
parameter_list|)
block|{
name|checkState
argument_list|(
name|change
operator|==
literal|null
argument_list|,
literal|"setStatus(Change.Status) only valid before creating change"
argument_list|)
expr_stmt|;
name|this
operator|.
name|status
operator|=
name|status
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setGroups (List<String> groups)
specifier|public
name|ChangeInserter
name|setGroups
parameter_list|(
name|List
argument_list|<
name|String
argument_list|>
name|groups
parameter_list|)
block|{
name|requireNonNull
argument_list|(
name|groups
argument_list|,
literal|"groups may not be empty"
argument_list|)
expr_stmt|;
name|checkState
argument_list|(
name|patchSet
operator|==
literal|null
argument_list|,
literal|"setGroups(Iterable<String>) only valid before creating change"
argument_list|)
expr_stmt|;
name|this
operator|.
name|groups
operator|=
name|groups
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setFireRevisionCreated (boolean fireRevisionCreated)
specifier|public
name|ChangeInserter
name|setFireRevisionCreated
parameter_list|(
name|boolean
name|fireRevisionCreated
parameter_list|)
block|{
name|this
operator|.
name|fireRevisionCreated
operator|=
name|fireRevisionCreated
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setSendMail (boolean sendMail)
specifier|public
name|ChangeInserter
name|setSendMail
parameter_list|(
name|boolean
name|sendMail
parameter_list|)
block|{
name|this
operator|.
name|sendMail
operator|=
name|sendMail
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setRequestScopePropagator (RequestScopePropagator r)
specifier|public
name|ChangeInserter
name|setRequestScopePropagator
parameter_list|(
name|RequestScopePropagator
name|r
parameter_list|)
block|{
name|this
operator|.
name|requestScopePropagator
operator|=
name|r
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setRevertOf (Change.Id revertOf)
specifier|public
name|ChangeInserter
name|setRevertOf
parameter_list|(
name|Change
operator|.
name|Id
name|revertOf
parameter_list|)
block|{
name|this
operator|.
name|revertOf
operator|=
name|revertOf
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|setPushCertificate (String cert)
specifier|public
name|void
name|setPushCertificate
parameter_list|(
name|String
name|cert
parameter_list|)
block|{
name|pushCert
operator|=
name|cert
expr_stmt|;
block|}
DECL|method|getPatchSet ()
specifier|public
name|PatchSet
name|getPatchSet
parameter_list|()
block|{
name|checkState
argument_list|(
name|patchSet
operator|!=
literal|null
argument_list|,
literal|"getPatchSet() only valid after creating change"
argument_list|)
expr_stmt|;
return|return
name|patchSet
return|;
block|}
DECL|method|setApprovals (Map<String, Short> approvals)
specifier|public
name|ChangeInserter
name|setApprovals
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|Short
argument_list|>
name|approvals
parameter_list|)
block|{
name|this
operator|.
name|approvals
operator|=
name|approvals
expr_stmt|;
return|return
name|this
return|;
block|}
comment|/**    * Set whether to include the new patch set ref update in this update.    *    *<p>If false, the caller is responsible for creating the patch set ref<strong>before</strong>    * executing the containing {@code BatchUpdate}.    *    *<p>Should not be used in new code, as it doesn't result in a single atomic batch ref update for    * code and NoteDb meta refs.    *    * @param updateRef whether to update the ref during {@code updateRepo}.    */
annotation|@
name|Deprecated
DECL|method|setUpdateRef (boolean updateRef)
specifier|public
name|ChangeInserter
name|setUpdateRef
parameter_list|(
name|boolean
name|updateRef
parameter_list|)
block|{
name|this
operator|.
name|updateRef
operator|=
name|updateRef
expr_stmt|;
return|return
name|this
return|;
block|}
DECL|method|getChangeMessage ()
specifier|public
name|ChangeMessage
name|getChangeMessage
parameter_list|()
block|{
if|if
condition|(
name|message
operator|==
literal|null
condition|)
block|{
return|return
literal|null
return|;
block|}
name|checkState
argument_list|(
name|changeMessage
operator|!=
literal|null
argument_list|,
literal|"getChangeMessage() only valid after inserting change"
argument_list|)
expr_stmt|;
return|return
name|changeMessage
return|;
block|}
DECL|method|getCommand ()
specifier|public
name|ReceiveCommand
name|getCommand
parameter_list|()
block|{
return|return
name|cmd
return|;
block|}
annotation|@
name|Override
DECL|method|updateRepo (RepoContext ctx)
specifier|public
name|void
name|updateRepo
parameter_list|(
name|RepoContext
name|ctx
parameter_list|)
throws|throws
name|ResourceConflictException
throws|,
name|IOException
block|{
name|cmd
operator|=
operator|new
name|ReceiveCommand
argument_list|(
name|ObjectId
operator|.
name|zeroId
argument_list|()
argument_list|,
name|commitId
argument_list|,
name|psId
operator|.
name|toRefName
argument_list|()
argument_list|)
expr_stmt|;
name|projectState
operator|=
name|projectCache
operator|.
name|checkedGet
argument_list|(
name|ctx
operator|.
name|getProject
argument_list|()
argument_list|)
expr_stmt|;
name|validate
argument_list|(
name|ctx
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|updateRef
condition|)
block|{
return|return;
block|}
name|ctx
operator|.
name|addRefUpdate
argument_list|(
name|cmd
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|updateChange (ChangeContext ctx)
specifier|public
name|boolean
name|updateChange
parameter_list|(
name|ChangeContext
name|ctx
parameter_list|)
throws|throws
name|RestApiException
throws|,
name|IOException
throws|,
name|PermissionBackendException
throws|,
name|ConfigInvalidException
block|{
name|change
operator|=
name|ctx
operator|.
name|getChange
argument_list|()
expr_stmt|;
comment|// Use defensive copy created by ChangeControl.
name|patchSetInfo
operator|=
name|patchSetInfoFactory
operator|.
name|get
argument_list|(
name|ctx
operator|.
name|getRevWalk
argument_list|()
argument_list|,
name|ctx
operator|.
name|getRevWalk
argument_list|()
operator|.
name|parseCommit
argument_list|(
name|commitId
argument_list|)
argument_list|,
name|psId
argument_list|)
expr_stmt|;
name|ctx
operator|.
name|getChange
argument_list|()
operator|.
name|setCurrentPatchSet
argument_list|(
name|patchSetInfo
argument_list|)
expr_stmt|;
name|ChangeUpdate
name|update
init|=
name|ctx
operator|.
name|getUpdate
argument_list|(
name|psId
argument_list|)
decl_stmt|;
name|update
operator|.
name|setChangeId
argument_list|(
name|change
operator|.
name|getKey
argument_list|()
operator|.
name|get
argument_list|()
argument_list|)
expr_stmt|;
name|update
operator|.
name|setSubjectForCommit
argument_list|(
literal|"Create change"
argument_list|)
expr_stmt|;
name|update
operator|.
name|setBranch
argument_list|(
name|change
operator|.
name|getDest
argument_list|()
operator|.
name|branch
argument_list|()
argument_list|)
expr_stmt|;
name|update
operator|.
name|setTopic
argument_list|(
name|change
operator|.
name|getTopic
argument_list|()
argument_list|)
expr_stmt|;
name|update
operator|.
name|setPsDescription
argument_list|(
name|patchSetDescription
argument_list|)
expr_stmt|;
name|update
operator|.
name|setPrivate
argument_list|(
name|isPrivate
argument_list|)
expr_stmt|;
name|update
operator|.
name|setWorkInProgress
argument_list|(
name|workInProgress
argument_list|)
expr_stmt|;
if|if
condition|(
name|revertOf
operator|!=
literal|null
condition|)
block|{
name|update
operator|.
name|setRevertOf
argument_list|(
name|revertOf
operator|.
name|get
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|List
argument_list|<
name|String
argument_list|>
name|newGroups
init|=
name|groups
decl_stmt|;
if|if
condition|(
name|newGroups
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
name|newGroups
operator|=
name|GroupCollector
operator|.
name|getDefaultGroups
argument_list|(
name|commitId
argument_list|)
expr_stmt|;
block|}
name|patchSet
operator|=
name|psUtil
operator|.
name|insert
argument_list|(
name|ctx
operator|.
name|getRevWalk
argument_list|()
argument_list|,
name|update
argument_list|,
name|psId
argument_list|,
name|commitId
argument_list|,
name|newGroups
argument_list|,
name|pushCert
argument_list|,
name|patchSetDescription
argument_list|)
expr_stmt|;
comment|/* TODO: fixStatusToMerged is used here because the tests      * (byStatusClosed() in AbstractQueryChangesTest)      * insert changes that are already merged,      * and setStatus may not be used to set the Status to merged      *      * is it possible to make the tests use the merge code path,      * instead of setting the status directly?      */
if|if
condition|(
name|change
operator|.
name|getStatus
argument_list|()
operator|==
name|Change
operator|.
name|Status
operator|.
name|MERGED
condition|)
block|{
name|update
operator|.
name|fixStatusToMerged
argument_list|(
operator|new
name|SubmissionId
argument_list|(
name|change
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|update
operator|.
name|setStatus
argument_list|(
name|change
operator|.
name|getStatus
argument_list|()
argument_list|)
expr_stmt|;
block|}
name|reviewerAdditions
operator|=
name|reviewerAdder
operator|.
name|prepare
argument_list|(
name|ctx
operator|.
name|getNotes
argument_list|()
argument_list|,
name|ctx
operator|.
name|getUser
argument_list|()
argument_list|,
name|getReviewerInputs
argument_list|()
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|Optional
argument_list|<
name|ReviewerAddition
argument_list|>
name|reviewerError
init|=
name|reviewerAdditions
operator|.
name|getFailures
argument_list|()
operator|.
name|stream
argument_list|()
operator|.
name|findFirst
argument_list|()
decl_stmt|;
if|if
condition|(
name|reviewerError
operator|.
name|isPresent
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|UnprocessableEntityException
argument_list|(
name|reviewerError
operator|.
name|get
argument_list|()
operator|.
name|result
operator|.
name|error
argument_list|)
throw|;
block|}
name|reviewerAdditions
operator|.
name|updateChange
argument_list|(
name|ctx
argument_list|,
name|patchSet
argument_list|)
expr_stmt|;
name|LabelTypes
name|labelTypes
init|=
name|projectState
operator|.
name|getLabelTypes
argument_list|()
decl_stmt|;
name|approvalsUtil
operator|.
name|addApprovalsForNewPatchSet
argument_list|(
name|update
argument_list|,
name|labelTypes
argument_list|,
name|patchSet
argument_list|,
name|ctx
operator|.
name|getUser
argument_list|()
argument_list|,
name|approvals
argument_list|)
expr_stmt|;
comment|// Check if approvals are changing in with this update. If so, add current user to reviewers.
comment|// Note that this is done separately as addReviewers is filtering out the change owner as
comment|// reviewer which is needed in several other code paths.
comment|// TODO(dborowitz): Still necessary?
if|if
condition|(
operator|!
name|approvals
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
name|update
operator|.
name|putReviewer
argument_list|(
name|ctx
operator|.
name|getAccountId
argument_list|()
argument_list|,
name|REVIEWER
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|message
operator|!=
literal|null
condition|)
block|{
name|changeMessage
operator|=
name|ChangeMessagesUtil
operator|.
name|newMessage
argument_list|(
name|patchSet
operator|.
name|id
argument_list|()
argument_list|,
name|ctx
operator|.
name|getUser
argument_list|()
argument_list|,
name|patchSet
operator|.
name|createdOn
argument_list|()
argument_list|,
name|message
argument_list|,
name|ChangeMessagesUtil
operator|.
name|uploadedPatchSetTag
argument_list|(
name|workInProgress
argument_list|)
argument_list|)
expr_stmt|;
name|cmUtil
operator|.
name|addChangeMessage
argument_list|(
name|update
argument_list|,
name|changeMessage
argument_list|)
expr_stmt|;
block|}
return|return
literal|true
return|;
block|}
annotation|@
name|Override
DECL|method|postUpdate (Context ctx)
specifier|public
name|void
name|postUpdate
parameter_list|(
name|Context
name|ctx
parameter_list|)
throws|throws
name|Exception
block|{
name|reviewerAdditions
operator|.
name|postUpdate
argument_list|(
name|ctx
argument_list|)
expr_stmt|;
name|NotifyResolver
operator|.
name|Result
name|notify
init|=
name|ctx
operator|.
name|getNotify
argument_list|(
name|change
operator|.
name|getId
argument_list|()
argument_list|)
decl_stmt|;
if|if
condition|(
name|sendMail
operator|&&
name|notify
operator|.
name|shouldNotify
argument_list|()
condition|)
block|{
name|Runnable
name|sender
init|=
operator|new
name|Runnable
argument_list|()
block|{
annotation|@
name|Override
specifier|public
name|void
name|run
parameter_list|()
block|{
try|try
block|{
name|CreateChangeSender
name|cm
init|=
name|createChangeSenderFactory
operator|.
name|create
argument_list|(
name|change
operator|.
name|getProject
argument_list|()
argument_list|,
name|change
operator|.
name|getId
argument_list|()
argument_list|)
decl_stmt|;
name|cm
operator|.
name|setFrom
argument_list|(
name|change
operator|.
name|getOwner
argument_list|()
argument_list|)
expr_stmt|;
name|cm
operator|.
name|setPatchSet
argument_list|(
name|patchSet
argument_list|,
name|patchSetInfo
argument_list|)
expr_stmt|;
name|cm
operator|.
name|setNotify
argument_list|(
name|notify
argument_list|)
expr_stmt|;
name|cm
operator|.
name|addReviewers
argument_list|(
name|reviewerAdditions
operator|.
name|flattenResults
argument_list|(
name|AddReviewersOp
operator|.
name|Result
operator|::
name|addedReviewers
argument_list|)
operator|.
name|stream
argument_list|()
operator|.
name|map
argument_list|(
name|PatchSetApproval
operator|::
name|accountId
argument_list|)
operator|.
name|collect
argument_list|(
name|toImmutableSet
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|cm
operator|.
name|addReviewersByEmail
argument_list|(
name|reviewerAdditions
operator|.
name|flattenResults
argument_list|(
name|AddReviewersOp
operator|.
name|Result
operator|::
name|addedReviewersByEmail
argument_list|)
argument_list|)
expr_stmt|;
name|cm
operator|.
name|addExtraCC
argument_list|(
name|reviewerAdditions
operator|.
name|flattenResults
argument_list|(
name|AddReviewersOp
operator|.
name|Result
operator|::
name|addedCCs
argument_list|)
argument_list|)
expr_stmt|;
name|cm
operator|.
name|addExtraCCByEmail
argument_list|(
name|reviewerAdditions
operator|.
name|flattenResults
argument_list|(
name|AddReviewersOp
operator|.
name|Result
operator|::
name|addedCCsByEmail
argument_list|)
argument_list|)
expr_stmt|;
name|cm
operator|.
name|send
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
name|logger
operator|.
name|atSevere
argument_list|()
operator|.
name|withCause
argument_list|(
name|e
argument_list|)
operator|.
name|log
argument_list|(
literal|"Cannot send email for new change %s"
argument_list|,
name|change
operator|.
name|getId
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
literal|"send-email newchange"
return|;
block|}
block|}
decl_stmt|;
if|if
condition|(
name|requestScopePropagator
operator|!=
literal|null
condition|)
block|{
annotation|@
name|SuppressWarnings
argument_list|(
literal|"unused"
argument_list|)
name|Future
argument_list|<
name|?
argument_list|>
name|possiblyIgnoredError
init|=
name|sendEmailExecutor
operator|.
name|submit
argument_list|(
name|requestScopePropagator
operator|.
name|wrap
argument_list|(
name|sender
argument_list|)
argument_list|)
decl_stmt|;
block|}
else|else
block|{
name|sender
operator|.
name|run
argument_list|()
expr_stmt|;
block|}
block|}
comment|/* For labels that are not set in this operation, show the "current" value      * of 0, and no oldValue as the value was not modified by this operation.      * For labels that are set in this operation, the value was modified, so      * show a transition from an oldValue of 0 to the new value.      */
if|if
condition|(
name|fireRevisionCreated
condition|)
block|{
name|revisionCreated
operator|.
name|fire
argument_list|(
name|change
argument_list|,
name|patchSet
argument_list|,
name|ctx
operator|.
name|getAccount
argument_list|()
argument_list|,
name|ctx
operator|.
name|getWhen
argument_list|()
argument_list|,
name|notify
argument_list|)
expr_stmt|;
if|if
condition|(
name|approvals
operator|!=
literal|null
operator|&&
operator|!
name|approvals
operator|.
name|isEmpty
argument_list|()
condition|)
block|{
name|List
argument_list|<
name|LabelType
argument_list|>
name|labels
init|=
name|projectState
operator|.
name|getLabelTypes
argument_list|(
name|change
operator|.
name|getDest
argument_list|()
argument_list|)
operator|.
name|getLabelTypes
argument_list|()
decl_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|Short
argument_list|>
name|allApprovals
init|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
decl_stmt|;
name|Map
argument_list|<
name|String
argument_list|,
name|Short
argument_list|>
name|oldApprovals
init|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
decl_stmt|;
for|for
control|(
name|LabelType
name|lt
range|:
name|labels
control|)
block|{
name|allApprovals
operator|.
name|put
argument_list|(
name|lt
operator|.
name|getName
argument_list|()
argument_list|,
operator|(
name|short
operator|)
literal|0
argument_list|)
expr_stmt|;
name|oldApprovals
operator|.
name|put
argument_list|(
name|lt
operator|.
name|getName
argument_list|()
argument_list|,
literal|null
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|String
argument_list|,
name|Short
argument_list|>
name|entry
range|:
name|approvals
operator|.
name|entrySet
argument_list|()
control|)
block|{
if|if
condition|(
name|entry
operator|.
name|getValue
argument_list|()
operator|!=
literal|0
condition|)
block|{
name|allApprovals
operator|.
name|put
argument_list|(
name|entry
operator|.
name|getKey
argument_list|()
argument_list|,
name|entry
operator|.
name|getValue
argument_list|()
argument_list|)
expr_stmt|;
name|oldApprovals
operator|.
name|put
argument_list|(
name|entry
operator|.
name|getKey
argument_list|()
argument_list|,
operator|(
name|short
operator|)
literal|0
argument_list|)
expr_stmt|;
block|}
block|}
name|commentAdded
operator|.
name|fire
argument_list|(
name|change
argument_list|,
name|patchSet
argument_list|,
name|ctx
operator|.
name|getAccount
argument_list|()
argument_list|,
literal|null
argument_list|,
name|allApprovals
argument_list|,
name|oldApprovals
argument_list|,
name|ctx
operator|.
name|getWhen
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
block|}
DECL|method|validate (RepoContext ctx)
specifier|private
name|void
name|validate
parameter_list|(
name|RepoContext
name|ctx
parameter_list|)
throws|throws
name|IOException
throws|,
name|ResourceConflictException
block|{
if|if
condition|(
operator|!
name|validate
condition|)
block|{
return|return;
block|}
try|try
block|{
try|try
init|(
name|CommitReceivedEvent
name|event
init|=
operator|new
name|CommitReceivedEvent
argument_list|(
name|cmd
argument_list|,
name|projectState
operator|.
name|getProject
argument_list|()
argument_list|,
name|change
operator|.
name|getDest
argument_list|()
operator|.
name|branch
argument_list|()
argument_list|,
name|ctx
operator|.
name|getRevWalk
argument_list|()
operator|.
name|getObjectReader
argument_list|()
argument_list|,
name|commitId
argument_list|,
name|ctx
operator|.
name|getIdentifiedUser
argument_list|()
argument_list|)
init|)
block|{
name|commitValidatorsFactory
operator|.
name|forGerritCommits
argument_list|(
name|permissionBackend
operator|.
name|user
argument_list|(
name|ctx
operator|.
name|getUser
argument_list|()
argument_list|)
operator|.
name|project
argument_list|(
name|ctx
operator|.
name|getProject
argument_list|()
argument_list|)
argument_list|,
name|BranchNameKey
operator|.
name|create
argument_list|(
name|ctx
operator|.
name|getProject
argument_list|()
argument_list|,
name|refName
argument_list|)
argument_list|,
name|ctx
operator|.
name|getIdentifiedUser
argument_list|()
argument_list|,
operator|new
name|NoSshInfo
argument_list|()
argument_list|,
name|ctx
operator|.
name|getRevWalk
argument_list|()
argument_list|,
name|change
argument_list|)
operator|.
name|validate
argument_list|(
name|event
argument_list|)
expr_stmt|;
block|}
block|}
catch|catch
parameter_list|(
name|CommitValidationException
name|e
parameter_list|)
block|{
throw|throw
operator|new
name|ResourceConflictException
argument_list|(
name|e
operator|.
name|getFullMessage
argument_list|()
argument_list|)
throw|;
block|}
block|}
DECL|method|newAddReviewerInput ( String reviewer, ReviewerState state)
specifier|private
specifier|static
name|InternalAddReviewerInput
name|newAddReviewerInput
parameter_list|(
name|String
name|reviewer
parameter_list|,
name|ReviewerState
name|state
parameter_list|)
block|{
comment|// Disable individual emails when adding reviewers, as all reviewers will receive the single
comment|// bulk new change email.
name|InternalAddReviewerInput
name|input
init|=
name|ReviewerAdder
operator|.
name|newAddReviewerInput
argument_list|(
name|reviewer
argument_list|,
name|state
argument_list|,
name|NotifyHandling
operator|.
name|NONE
argument_list|)
decl_stmt|;
comment|// Ignore failures for reasons like the reviewer being inactive or being unable to see the
comment|// change. This is required for the push path, where it automatically sets reviewers from
comment|// certain commit footers: putting a nonexistent user in a footer should not cause an error. In
comment|// theory we could provide finer control to do this for some reviewers and not others, but it's
comment|// not worth complicating the ChangeInserter interface further at this time.
name|input
operator|.
name|otherFailureBehavior
operator|=
name|ReviewerAdder
operator|.
name|FailureBehavior
operator|.
name|IGNORE
expr_stmt|;
return|return
name|input
return|;
block|}
DECL|method|getReviewerInputs ()
specifier|private
name|ImmutableList
argument_list|<
name|InternalAddReviewerInput
argument_list|>
name|getReviewerInputs
parameter_list|()
block|{
return|return
name|Streams
operator|.
name|concat
argument_list|(
name|reviewerInputs
operator|.
name|stream
argument_list|()
argument_list|,
name|Streams
operator|.
name|stream
argument_list|(
name|newAddReviewerInputFromCommitIdentity
argument_list|(
name|change
argument_list|,
name|patchSetInfo
operator|.
name|getAuthor
argument_list|()
operator|.
name|getAccount
argument_list|()
argument_list|,
name|NotifyHandling
operator|.
name|NONE
argument_list|)
argument_list|)
argument_list|,
name|Streams
operator|.
name|stream
argument_list|(
name|newAddReviewerInputFromCommitIdentity
argument_list|(
name|change
argument_list|,
name|patchSetInfo
operator|.
name|getCommitter
argument_list|()
operator|.
name|getAccount
argument_list|()
argument_list|,
name|NotifyHandling
operator|.
name|NONE
argument_list|)
argument_list|)
argument_list|)
operator|.
name|collect
argument_list|(
name|toImmutableList
argument_list|()
argument_list|)
return|;
block|}
block|}
end_class

end_unit

