begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|// Copyright (C) 2019 The Android Open Source Project
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// Licensed under the Apache License, Version 2.0 (the "License");
end_comment

begin_comment
comment|// you may not use this file except in compliance with the License.
end_comment

begin_comment
comment|// You may obtain a copy of the License at
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// http://www.apache.org/licenses/LICENSE-2.0
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// Unless required by applicable law or agreed to in writing, software
end_comment

begin_comment
comment|// distributed under the License is distributed on an "AS IS" BASIS,
end_comment

begin_comment
comment|// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
end_comment

begin_comment
comment|// See the License for the specific language governing permissions and
end_comment

begin_comment
comment|// limitations under the License.
end_comment

begin_package
DECL|package|com.google.gerrit.server.account
package|package
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|account
package|;
end_package

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|auto
operator|.
name|value
operator|.
name|AutoValue
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|collect
operator|.
name|ImmutableList
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|common
operator|.
name|Nullable
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|DiffPreferencesInfo
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|DiffPreferencesInfo
operator|.
name|Whitespace
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|EditPreferencesInfo
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|GeneralPreferencesInfo
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|GeneralPreferencesInfo
operator|.
name|DateFormat
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|GeneralPreferencesInfo
operator|.
name|DefaultBase
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|GeneralPreferencesInfo
operator|.
name|DiffView
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|GeneralPreferencesInfo
operator|.
name|EmailFormat
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|GeneralPreferencesInfo
operator|.
name|EmailStrategy
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|GeneralPreferencesInfo
operator|.
name|TimeFormat
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|KeyMapType
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|MenuItem
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|client
operator|.
name|Theme
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Optional
import|;
end_import

begin_class
annotation|@
name|AutoValue
DECL|class|Preferences
specifier|public
specifier|abstract
class|class
name|Preferences
block|{
annotation|@
name|AutoValue
DECL|class|General
specifier|public
specifier|abstract
specifier|static
class|class
name|General
block|{
DECL|method|changesPerPage ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Integer
argument_list|>
name|changesPerPage
parameter_list|()
function_decl|;
DECL|method|downloadScheme ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|String
argument_list|>
name|downloadScheme
parameter_list|()
function_decl|;
DECL|method|dateFormat ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|DateFormat
argument_list|>
name|dateFormat
parameter_list|()
function_decl|;
DECL|method|timeFormat ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|TimeFormat
argument_list|>
name|timeFormat
parameter_list|()
function_decl|;
DECL|method|expandInlineDiffs ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|expandInlineDiffs
parameter_list|()
function_decl|;
DECL|method|highlightAssigneeInChangeTable ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|highlightAssigneeInChangeTable
parameter_list|()
function_decl|;
DECL|method|relativeDateInChangeTable ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|relativeDateInChangeTable
parameter_list|()
function_decl|;
DECL|method|diffView ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|DiffView
argument_list|>
name|diffView
parameter_list|()
function_decl|;
DECL|method|sizeBarInChangeTable ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|sizeBarInChangeTable
parameter_list|()
function_decl|;
DECL|method|legacycidInChangeTable ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|legacycidInChangeTable
parameter_list|()
function_decl|;
DECL|method|muteCommonPathPrefixes ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|muteCommonPathPrefixes
parameter_list|()
function_decl|;
DECL|method|signedOffBy ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|signedOffBy
parameter_list|()
function_decl|;
DECL|method|emailStrategy ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|EmailStrategy
argument_list|>
name|emailStrategy
parameter_list|()
function_decl|;
DECL|method|emailFormat ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|EmailFormat
argument_list|>
name|emailFormat
parameter_list|()
function_decl|;
DECL|method|defaultBaseForMerges ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|DefaultBase
argument_list|>
name|defaultBaseForMerges
parameter_list|()
function_decl|;
DECL|method|publishCommentsOnPush ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|publishCommentsOnPush
parameter_list|()
function_decl|;
DECL|method|workInProgressByDefault ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|workInProgressByDefault
parameter_list|()
function_decl|;
DECL|method|my ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|ImmutableList
argument_list|<
name|MenuItem
argument_list|>
argument_list|>
name|my
parameter_list|()
function_decl|;
DECL|method|changeTable ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|ImmutableList
argument_list|<
name|String
argument_list|>
argument_list|>
name|changeTable
parameter_list|()
function_decl|;
annotation|@
name|AutoValue
operator|.
name|Builder
DECL|class|Builder
specifier|public
specifier|abstract
specifier|static
class|class
name|Builder
block|{
DECL|method|changesPerPage (@ullable Integer val)
specifier|abstract
name|Builder
name|changesPerPage
parameter_list|(
annotation|@
name|Nullable
name|Integer
name|val
parameter_list|)
function_decl|;
DECL|method|downloadScheme (@ullable String val)
specifier|abstract
name|Builder
name|downloadScheme
parameter_list|(
annotation|@
name|Nullable
name|String
name|val
parameter_list|)
function_decl|;
DECL|method|dateFormat (@ullable DateFormat val)
specifier|abstract
name|Builder
name|dateFormat
parameter_list|(
annotation|@
name|Nullable
name|DateFormat
name|val
parameter_list|)
function_decl|;
DECL|method|timeFormat (@ullable TimeFormat val)
specifier|abstract
name|Builder
name|timeFormat
parameter_list|(
annotation|@
name|Nullable
name|TimeFormat
name|val
parameter_list|)
function_decl|;
DECL|method|expandInlineDiffs (@ullable Boolean val)
specifier|abstract
name|Builder
name|expandInlineDiffs
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|highlightAssigneeInChangeTable (@ullable Boolean val)
specifier|abstract
name|Builder
name|highlightAssigneeInChangeTable
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|relativeDateInChangeTable (@ullable Boolean val)
specifier|abstract
name|Builder
name|relativeDateInChangeTable
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|diffView (@ullable DiffView val)
specifier|abstract
name|Builder
name|diffView
parameter_list|(
annotation|@
name|Nullable
name|DiffView
name|val
parameter_list|)
function_decl|;
DECL|method|sizeBarInChangeTable (@ullable Boolean val)
specifier|abstract
name|Builder
name|sizeBarInChangeTable
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|legacycidInChangeTable (@ullable Boolean val)
specifier|abstract
name|Builder
name|legacycidInChangeTable
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|muteCommonPathPrefixes (@ullable Boolean val)
specifier|abstract
name|Builder
name|muteCommonPathPrefixes
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|signedOffBy (@ullable Boolean val)
specifier|abstract
name|Builder
name|signedOffBy
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|emailStrategy (@ullable EmailStrategy val)
specifier|abstract
name|Builder
name|emailStrategy
parameter_list|(
annotation|@
name|Nullable
name|EmailStrategy
name|val
parameter_list|)
function_decl|;
DECL|method|emailFormat (@ullable EmailFormat val)
specifier|abstract
name|Builder
name|emailFormat
parameter_list|(
annotation|@
name|Nullable
name|EmailFormat
name|val
parameter_list|)
function_decl|;
DECL|method|defaultBaseForMerges (@ullable DefaultBase val)
specifier|abstract
name|Builder
name|defaultBaseForMerges
parameter_list|(
annotation|@
name|Nullable
name|DefaultBase
name|val
parameter_list|)
function_decl|;
DECL|method|publishCommentsOnPush (@ullable Boolean val)
specifier|abstract
name|Builder
name|publishCommentsOnPush
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|workInProgressByDefault (@ullable Boolean val)
specifier|abstract
name|Builder
name|workInProgressByDefault
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|my (@ullable ImmutableList<MenuItem> val)
specifier|abstract
name|Builder
name|my
parameter_list|(
annotation|@
name|Nullable
name|ImmutableList
argument_list|<
name|MenuItem
argument_list|>
name|val
parameter_list|)
function_decl|;
DECL|method|changeTable (@ullable ImmutableList<String> val)
specifier|abstract
name|Builder
name|changeTable
parameter_list|(
annotation|@
name|Nullable
name|ImmutableList
argument_list|<
name|String
argument_list|>
name|val
parameter_list|)
function_decl|;
DECL|method|build ()
specifier|abstract
name|General
name|build
parameter_list|()
function_decl|;
block|}
DECL|method|fromInfo (GeneralPreferencesInfo info)
specifier|public
specifier|static
name|General
name|fromInfo
parameter_list|(
name|GeneralPreferencesInfo
name|info
parameter_list|)
block|{
return|return
operator|(
operator|new
name|AutoValue_Preferences_General
operator|.
name|Builder
argument_list|()
operator|)
operator|.
name|changesPerPage
argument_list|(
name|info
operator|.
name|changesPerPage
argument_list|)
operator|.
name|downloadScheme
argument_list|(
name|info
operator|.
name|downloadScheme
argument_list|)
operator|.
name|dateFormat
argument_list|(
name|info
operator|.
name|dateFormat
argument_list|)
operator|.
name|timeFormat
argument_list|(
name|info
operator|.
name|timeFormat
argument_list|)
operator|.
name|expandInlineDiffs
argument_list|(
name|info
operator|.
name|expandInlineDiffs
argument_list|)
operator|.
name|highlightAssigneeInChangeTable
argument_list|(
name|info
operator|.
name|highlightAssigneeInChangeTable
argument_list|)
operator|.
name|relativeDateInChangeTable
argument_list|(
name|info
operator|.
name|relativeDateInChangeTable
argument_list|)
operator|.
name|diffView
argument_list|(
name|info
operator|.
name|diffView
argument_list|)
operator|.
name|sizeBarInChangeTable
argument_list|(
name|info
operator|.
name|sizeBarInChangeTable
argument_list|)
operator|.
name|legacycidInChangeTable
argument_list|(
name|info
operator|.
name|legacycidInChangeTable
argument_list|)
operator|.
name|muteCommonPathPrefixes
argument_list|(
name|info
operator|.
name|muteCommonPathPrefixes
argument_list|)
operator|.
name|signedOffBy
argument_list|(
name|info
operator|.
name|signedOffBy
argument_list|)
operator|.
name|emailStrategy
argument_list|(
name|info
operator|.
name|emailStrategy
argument_list|)
operator|.
name|emailFormat
argument_list|(
name|info
operator|.
name|emailFormat
argument_list|)
operator|.
name|defaultBaseForMerges
argument_list|(
name|info
operator|.
name|defaultBaseForMerges
argument_list|)
operator|.
name|publishCommentsOnPush
argument_list|(
name|info
operator|.
name|publishCommentsOnPush
argument_list|)
operator|.
name|workInProgressByDefault
argument_list|(
name|info
operator|.
name|workInProgressByDefault
argument_list|)
operator|.
name|my
argument_list|(
name|info
operator|.
name|my
operator|==
literal|null
condition|?
literal|null
else|:
name|ImmutableList
operator|.
name|copyOf
argument_list|(
name|info
operator|.
name|my
argument_list|)
argument_list|)
operator|.
name|changeTable
argument_list|(
name|info
operator|.
name|changeTable
operator|==
literal|null
condition|?
literal|null
else|:
name|ImmutableList
operator|.
name|copyOf
argument_list|(
name|info
operator|.
name|changeTable
argument_list|)
argument_list|)
operator|.
name|build
argument_list|()
return|;
block|}
DECL|method|toInfo ()
specifier|public
name|GeneralPreferencesInfo
name|toInfo
parameter_list|()
block|{
name|GeneralPreferencesInfo
name|info
init|=
operator|new
name|GeneralPreferencesInfo
argument_list|()
decl_stmt|;
name|info
operator|.
name|changesPerPage
operator|=
name|changesPerPage
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|downloadScheme
operator|=
name|downloadScheme
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|dateFormat
operator|=
name|dateFormat
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|timeFormat
operator|=
name|timeFormat
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|expandInlineDiffs
operator|=
name|expandInlineDiffs
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|highlightAssigneeInChangeTable
operator|=
name|highlightAssigneeInChangeTable
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|relativeDateInChangeTable
operator|=
name|relativeDateInChangeTable
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|diffView
operator|=
name|diffView
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|sizeBarInChangeTable
operator|=
name|sizeBarInChangeTable
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|legacycidInChangeTable
operator|=
name|legacycidInChangeTable
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|muteCommonPathPrefixes
operator|=
name|muteCommonPathPrefixes
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|signedOffBy
operator|=
name|signedOffBy
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|emailStrategy
operator|=
name|emailStrategy
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|emailFormat
operator|=
name|emailFormat
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|defaultBaseForMerges
operator|=
name|defaultBaseForMerges
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|publishCommentsOnPush
operator|=
name|publishCommentsOnPush
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|workInProgressByDefault
operator|=
name|workInProgressByDefault
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|my
operator|=
name|my
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|changeTable
operator|=
name|changeTable
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
return|return
name|info
return|;
block|}
block|}
annotation|@
name|AutoValue
DECL|class|Edit
specifier|public
specifier|abstract
specifier|static
class|class
name|Edit
block|{
DECL|method|tabSize ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Integer
argument_list|>
name|tabSize
parameter_list|()
function_decl|;
DECL|method|lineLength ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Integer
argument_list|>
name|lineLength
parameter_list|()
function_decl|;
DECL|method|indentUnit ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Integer
argument_list|>
name|indentUnit
parameter_list|()
function_decl|;
DECL|method|cursorBlinkRate ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Integer
argument_list|>
name|cursorBlinkRate
parameter_list|()
function_decl|;
DECL|method|hideTopMenu ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|hideTopMenu
parameter_list|()
function_decl|;
DECL|method|showTabs ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|showTabs
parameter_list|()
function_decl|;
DECL|method|showWhitespaceErrors ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|showWhitespaceErrors
parameter_list|()
function_decl|;
DECL|method|syntaxHighlighting ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|syntaxHighlighting
parameter_list|()
function_decl|;
DECL|method|hideLineNumbers ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|hideLineNumbers
parameter_list|()
function_decl|;
DECL|method|matchBrackets ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|matchBrackets
parameter_list|()
function_decl|;
DECL|method|lineWrapping ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|lineWrapping
parameter_list|()
function_decl|;
DECL|method|indentWithTabs ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|indentWithTabs
parameter_list|()
function_decl|;
DECL|method|autoCloseBrackets ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|autoCloseBrackets
parameter_list|()
function_decl|;
DECL|method|showBase ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|showBase
parameter_list|()
function_decl|;
DECL|method|theme ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Theme
argument_list|>
name|theme
parameter_list|()
function_decl|;
DECL|method|keyMapType ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|KeyMapType
argument_list|>
name|keyMapType
parameter_list|()
function_decl|;
annotation|@
name|AutoValue
operator|.
name|Builder
DECL|class|Builder
specifier|public
specifier|abstract
specifier|static
class|class
name|Builder
block|{
DECL|method|tabSize (@ullable Integer val)
specifier|abstract
name|Builder
name|tabSize
parameter_list|(
annotation|@
name|Nullable
name|Integer
name|val
parameter_list|)
function_decl|;
DECL|method|lineLength (@ullable Integer val)
specifier|abstract
name|Builder
name|lineLength
parameter_list|(
annotation|@
name|Nullable
name|Integer
name|val
parameter_list|)
function_decl|;
DECL|method|indentUnit (@ullable Integer val)
specifier|abstract
name|Builder
name|indentUnit
parameter_list|(
annotation|@
name|Nullable
name|Integer
name|val
parameter_list|)
function_decl|;
DECL|method|cursorBlinkRate (@ullable Integer val)
specifier|abstract
name|Builder
name|cursorBlinkRate
parameter_list|(
annotation|@
name|Nullable
name|Integer
name|val
parameter_list|)
function_decl|;
DECL|method|hideTopMenu (@ullable Boolean val)
specifier|abstract
name|Builder
name|hideTopMenu
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|showTabs (@ullable Boolean val)
specifier|abstract
name|Builder
name|showTabs
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|showWhitespaceErrors (@ullable Boolean val)
specifier|abstract
name|Builder
name|showWhitespaceErrors
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|syntaxHighlighting (@ullable Boolean val)
specifier|abstract
name|Builder
name|syntaxHighlighting
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|hideLineNumbers (@ullable Boolean val)
specifier|abstract
name|Builder
name|hideLineNumbers
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|matchBrackets (@ullable Boolean val)
specifier|abstract
name|Builder
name|matchBrackets
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|lineWrapping (@ullable Boolean val)
specifier|abstract
name|Builder
name|lineWrapping
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|indentWithTabs (@ullable Boolean val)
specifier|abstract
name|Builder
name|indentWithTabs
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|autoCloseBrackets (@ullable Boolean val)
specifier|abstract
name|Builder
name|autoCloseBrackets
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|showBase (@ullable Boolean val)
specifier|abstract
name|Builder
name|showBase
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|theme (@ullable Theme val)
specifier|abstract
name|Builder
name|theme
parameter_list|(
annotation|@
name|Nullable
name|Theme
name|val
parameter_list|)
function_decl|;
DECL|method|keyMapType (@ullable KeyMapType val)
specifier|abstract
name|Builder
name|keyMapType
parameter_list|(
annotation|@
name|Nullable
name|KeyMapType
name|val
parameter_list|)
function_decl|;
DECL|method|build ()
specifier|abstract
name|Edit
name|build
parameter_list|()
function_decl|;
block|}
DECL|method|fromInfo (EditPreferencesInfo info)
specifier|public
specifier|static
name|Edit
name|fromInfo
parameter_list|(
name|EditPreferencesInfo
name|info
parameter_list|)
block|{
return|return
operator|(
operator|new
name|AutoValue_Preferences_Edit
operator|.
name|Builder
argument_list|()
operator|)
operator|.
name|tabSize
argument_list|(
name|info
operator|.
name|tabSize
argument_list|)
operator|.
name|lineLength
argument_list|(
name|info
operator|.
name|lineLength
argument_list|)
operator|.
name|indentUnit
argument_list|(
name|info
operator|.
name|indentUnit
argument_list|)
operator|.
name|cursorBlinkRate
argument_list|(
name|info
operator|.
name|cursorBlinkRate
argument_list|)
operator|.
name|hideTopMenu
argument_list|(
name|info
operator|.
name|hideTopMenu
argument_list|)
operator|.
name|showTabs
argument_list|(
name|info
operator|.
name|showTabs
argument_list|)
operator|.
name|showWhitespaceErrors
argument_list|(
name|info
operator|.
name|showWhitespaceErrors
argument_list|)
operator|.
name|syntaxHighlighting
argument_list|(
name|info
operator|.
name|syntaxHighlighting
argument_list|)
operator|.
name|hideLineNumbers
argument_list|(
name|info
operator|.
name|hideLineNumbers
argument_list|)
operator|.
name|matchBrackets
argument_list|(
name|info
operator|.
name|matchBrackets
argument_list|)
operator|.
name|lineWrapping
argument_list|(
name|info
operator|.
name|lineWrapping
argument_list|)
operator|.
name|indentWithTabs
argument_list|(
name|info
operator|.
name|indentWithTabs
argument_list|)
operator|.
name|autoCloseBrackets
argument_list|(
name|info
operator|.
name|autoCloseBrackets
argument_list|)
operator|.
name|showBase
argument_list|(
name|info
operator|.
name|showBase
argument_list|)
operator|.
name|theme
argument_list|(
name|info
operator|.
name|theme
argument_list|)
operator|.
name|keyMapType
argument_list|(
name|info
operator|.
name|keyMapType
argument_list|)
operator|.
name|build
argument_list|()
return|;
block|}
DECL|method|toInfo ()
specifier|public
name|EditPreferencesInfo
name|toInfo
parameter_list|()
block|{
name|EditPreferencesInfo
name|info
init|=
operator|new
name|EditPreferencesInfo
argument_list|()
decl_stmt|;
name|info
operator|.
name|tabSize
operator|=
name|tabSize
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|lineLength
operator|=
name|lineLength
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|indentUnit
operator|=
name|indentUnit
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|cursorBlinkRate
operator|=
name|cursorBlinkRate
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|hideTopMenu
operator|=
name|hideTopMenu
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|showTabs
operator|=
name|showTabs
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|showWhitespaceErrors
operator|=
name|showWhitespaceErrors
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|syntaxHighlighting
operator|=
name|syntaxHighlighting
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|hideLineNumbers
operator|=
name|hideLineNumbers
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|matchBrackets
operator|=
name|matchBrackets
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|lineWrapping
operator|=
name|lineWrapping
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|indentWithTabs
operator|=
name|indentWithTabs
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|autoCloseBrackets
operator|=
name|autoCloseBrackets
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|showBase
operator|=
name|showBase
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|theme
operator|=
name|theme
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|keyMapType
operator|=
name|keyMapType
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
return|return
name|info
return|;
block|}
block|}
annotation|@
name|AutoValue
DECL|class|Diff
specifier|public
specifier|abstract
specifier|static
class|class
name|Diff
block|{
DECL|method|context ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Integer
argument_list|>
name|context
parameter_list|()
function_decl|;
DECL|method|tabSize ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Integer
argument_list|>
name|tabSize
parameter_list|()
function_decl|;
DECL|method|fontSize ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Integer
argument_list|>
name|fontSize
parameter_list|()
function_decl|;
DECL|method|lineLength ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Integer
argument_list|>
name|lineLength
parameter_list|()
function_decl|;
DECL|method|cursorBlinkRate ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Integer
argument_list|>
name|cursorBlinkRate
parameter_list|()
function_decl|;
DECL|method|expandAllComments ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|expandAllComments
parameter_list|()
function_decl|;
DECL|method|intralineDifference ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|intralineDifference
parameter_list|()
function_decl|;
DECL|method|manualReview ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|manualReview
parameter_list|()
function_decl|;
DECL|method|showLineEndings ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|showLineEndings
parameter_list|()
function_decl|;
DECL|method|showTabs ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|showTabs
parameter_list|()
function_decl|;
DECL|method|showWhitespaceErrors ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|showWhitespaceErrors
parameter_list|()
function_decl|;
DECL|method|syntaxHighlighting ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|syntaxHighlighting
parameter_list|()
function_decl|;
DECL|method|hideTopMenu ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|hideTopMenu
parameter_list|()
function_decl|;
DECL|method|autoHideDiffTableHeader ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|autoHideDiffTableHeader
parameter_list|()
function_decl|;
DECL|method|hideLineNumbers ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|hideLineNumbers
parameter_list|()
function_decl|;
DECL|method|renderEntireFile ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|renderEntireFile
parameter_list|()
function_decl|;
DECL|method|hideEmptyPane ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|hideEmptyPane
parameter_list|()
function_decl|;
DECL|method|matchBrackets ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|matchBrackets
parameter_list|()
function_decl|;
DECL|method|lineWrapping ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|lineWrapping
parameter_list|()
function_decl|;
DECL|method|theme ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Theme
argument_list|>
name|theme
parameter_list|()
function_decl|;
DECL|method|ignoreWhitespace ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Whitespace
argument_list|>
name|ignoreWhitespace
parameter_list|()
function_decl|;
DECL|method|retainHeader ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|retainHeader
parameter_list|()
function_decl|;
DECL|method|skipDeleted ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|skipDeleted
parameter_list|()
function_decl|;
DECL|method|skipUnchanged ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|skipUnchanged
parameter_list|()
function_decl|;
DECL|method|skipUncommented ()
specifier|public
specifier|abstract
name|Optional
argument_list|<
name|Boolean
argument_list|>
name|skipUncommented
parameter_list|()
function_decl|;
annotation|@
name|AutoValue
operator|.
name|Builder
DECL|class|Builder
specifier|public
specifier|abstract
specifier|static
class|class
name|Builder
block|{
DECL|method|context (@ullable Integer val)
specifier|abstract
name|Builder
name|context
parameter_list|(
annotation|@
name|Nullable
name|Integer
name|val
parameter_list|)
function_decl|;
DECL|method|tabSize (@ullable Integer val)
specifier|abstract
name|Builder
name|tabSize
parameter_list|(
annotation|@
name|Nullable
name|Integer
name|val
parameter_list|)
function_decl|;
DECL|method|fontSize (@ullable Integer val)
specifier|abstract
name|Builder
name|fontSize
parameter_list|(
annotation|@
name|Nullable
name|Integer
name|val
parameter_list|)
function_decl|;
DECL|method|lineLength (@ullable Integer val)
specifier|abstract
name|Builder
name|lineLength
parameter_list|(
annotation|@
name|Nullable
name|Integer
name|val
parameter_list|)
function_decl|;
DECL|method|cursorBlinkRate (@ullable Integer val)
specifier|abstract
name|Builder
name|cursorBlinkRate
parameter_list|(
annotation|@
name|Nullable
name|Integer
name|val
parameter_list|)
function_decl|;
DECL|method|expandAllComments (@ullable Boolean val)
specifier|abstract
name|Builder
name|expandAllComments
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|intralineDifference (@ullable Boolean val)
specifier|abstract
name|Builder
name|intralineDifference
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|manualReview (@ullable Boolean val)
specifier|abstract
name|Builder
name|manualReview
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|showLineEndings (@ullable Boolean val)
specifier|abstract
name|Builder
name|showLineEndings
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|showTabs (@ullable Boolean val)
specifier|abstract
name|Builder
name|showTabs
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|showWhitespaceErrors (@ullable Boolean val)
specifier|abstract
name|Builder
name|showWhitespaceErrors
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|syntaxHighlighting (@ullable Boolean val)
specifier|abstract
name|Builder
name|syntaxHighlighting
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|hideTopMenu (@ullable Boolean val)
specifier|abstract
name|Builder
name|hideTopMenu
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|autoHideDiffTableHeader (@ullable Boolean val)
specifier|abstract
name|Builder
name|autoHideDiffTableHeader
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|hideLineNumbers (@ullable Boolean val)
specifier|abstract
name|Builder
name|hideLineNumbers
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|renderEntireFile (@ullable Boolean val)
specifier|abstract
name|Builder
name|renderEntireFile
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|hideEmptyPane (@ullable Boolean val)
specifier|abstract
name|Builder
name|hideEmptyPane
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|matchBrackets (@ullable Boolean val)
specifier|abstract
name|Builder
name|matchBrackets
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|lineWrapping (@ullable Boolean val)
specifier|abstract
name|Builder
name|lineWrapping
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|theme (@ullable Theme val)
specifier|abstract
name|Builder
name|theme
parameter_list|(
annotation|@
name|Nullable
name|Theme
name|val
parameter_list|)
function_decl|;
DECL|method|ignoreWhitespace (@ullable Whitespace val)
specifier|abstract
name|Builder
name|ignoreWhitespace
parameter_list|(
annotation|@
name|Nullable
name|Whitespace
name|val
parameter_list|)
function_decl|;
DECL|method|retainHeader (@ullable Boolean val)
specifier|abstract
name|Builder
name|retainHeader
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|skipDeleted (@ullable Boolean val)
specifier|abstract
name|Builder
name|skipDeleted
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|skipUnchanged (@ullable Boolean val)
specifier|abstract
name|Builder
name|skipUnchanged
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|skipUncommented (@ullable Boolean val)
specifier|abstract
name|Builder
name|skipUncommented
parameter_list|(
annotation|@
name|Nullable
name|Boolean
name|val
parameter_list|)
function_decl|;
DECL|method|build ()
specifier|abstract
name|Diff
name|build
parameter_list|()
function_decl|;
block|}
DECL|method|fromInfo (DiffPreferencesInfo info)
specifier|public
specifier|static
name|Diff
name|fromInfo
parameter_list|(
name|DiffPreferencesInfo
name|info
parameter_list|)
block|{
return|return
operator|(
operator|new
name|AutoValue_Preferences_Diff
operator|.
name|Builder
argument_list|()
operator|)
operator|.
name|context
argument_list|(
name|info
operator|.
name|context
argument_list|)
operator|.
name|tabSize
argument_list|(
name|info
operator|.
name|tabSize
argument_list|)
operator|.
name|fontSize
argument_list|(
name|info
operator|.
name|fontSize
argument_list|)
operator|.
name|lineLength
argument_list|(
name|info
operator|.
name|lineLength
argument_list|)
operator|.
name|cursorBlinkRate
argument_list|(
name|info
operator|.
name|cursorBlinkRate
argument_list|)
operator|.
name|expandAllComments
argument_list|(
name|info
operator|.
name|expandAllComments
argument_list|)
operator|.
name|intralineDifference
argument_list|(
name|info
operator|.
name|intralineDifference
argument_list|)
operator|.
name|manualReview
argument_list|(
name|info
operator|.
name|manualReview
argument_list|)
operator|.
name|showLineEndings
argument_list|(
name|info
operator|.
name|showLineEndings
argument_list|)
operator|.
name|showTabs
argument_list|(
name|info
operator|.
name|showTabs
argument_list|)
operator|.
name|showWhitespaceErrors
argument_list|(
name|info
operator|.
name|showWhitespaceErrors
argument_list|)
operator|.
name|syntaxHighlighting
argument_list|(
name|info
operator|.
name|syntaxHighlighting
argument_list|)
operator|.
name|hideTopMenu
argument_list|(
name|info
operator|.
name|hideTopMenu
argument_list|)
operator|.
name|autoHideDiffTableHeader
argument_list|(
name|info
operator|.
name|autoHideDiffTableHeader
argument_list|)
operator|.
name|hideLineNumbers
argument_list|(
name|info
operator|.
name|hideLineNumbers
argument_list|)
operator|.
name|renderEntireFile
argument_list|(
name|info
operator|.
name|renderEntireFile
argument_list|)
operator|.
name|hideEmptyPane
argument_list|(
name|info
operator|.
name|hideEmptyPane
argument_list|)
operator|.
name|matchBrackets
argument_list|(
name|info
operator|.
name|matchBrackets
argument_list|)
operator|.
name|lineWrapping
argument_list|(
name|info
operator|.
name|lineWrapping
argument_list|)
operator|.
name|theme
argument_list|(
name|info
operator|.
name|theme
argument_list|)
operator|.
name|ignoreWhitespace
argument_list|(
name|info
operator|.
name|ignoreWhitespace
argument_list|)
operator|.
name|retainHeader
argument_list|(
name|info
operator|.
name|retainHeader
argument_list|)
operator|.
name|skipDeleted
argument_list|(
name|info
operator|.
name|skipDeleted
argument_list|)
operator|.
name|skipUnchanged
argument_list|(
name|info
operator|.
name|skipUnchanged
argument_list|)
operator|.
name|skipUncommented
argument_list|(
name|info
operator|.
name|skipUncommented
argument_list|)
operator|.
name|build
argument_list|()
return|;
block|}
DECL|method|toInfo ()
specifier|public
name|DiffPreferencesInfo
name|toInfo
parameter_list|()
block|{
name|DiffPreferencesInfo
name|info
init|=
operator|new
name|DiffPreferencesInfo
argument_list|()
decl_stmt|;
name|info
operator|.
name|context
operator|=
name|context
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|tabSize
operator|=
name|tabSize
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|fontSize
operator|=
name|fontSize
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|lineLength
operator|=
name|lineLength
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|cursorBlinkRate
operator|=
name|cursorBlinkRate
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|expandAllComments
operator|=
name|expandAllComments
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|intralineDifference
operator|=
name|intralineDifference
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|manualReview
operator|=
name|manualReview
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|showLineEndings
operator|=
name|showLineEndings
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|showTabs
operator|=
name|showTabs
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|showWhitespaceErrors
operator|=
name|showWhitespaceErrors
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|syntaxHighlighting
operator|=
name|syntaxHighlighting
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|hideTopMenu
operator|=
name|hideTopMenu
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|autoHideDiffTableHeader
operator|=
name|autoHideDiffTableHeader
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|hideLineNumbers
operator|=
name|hideLineNumbers
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|renderEntireFile
operator|=
name|renderEntireFile
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|hideEmptyPane
operator|=
name|hideEmptyPane
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|matchBrackets
operator|=
name|matchBrackets
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|lineWrapping
operator|=
name|lineWrapping
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|theme
operator|=
name|theme
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|ignoreWhitespace
operator|=
name|ignoreWhitespace
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|retainHeader
operator|=
name|retainHeader
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|skipDeleted
operator|=
name|skipDeleted
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|skipUnchanged
operator|=
name|skipUnchanged
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|info
operator|.
name|skipUncommented
operator|=
name|skipUncommented
argument_list|()
operator|.
name|orElse
argument_list|(
literal|null
argument_list|)
expr_stmt|;
return|return
name|info
return|;
block|}
block|}
block|}
end_class

end_unit

