begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|// Copyright (C) 2009 The Android Open Source Project
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// Licensed under the Apache License, Version 2.0 (the "License");
end_comment

begin_comment
comment|// you may not use this file except in compliance with the License.
end_comment

begin_comment
comment|// You may obtain a copy of the License at
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// http://www.apache.org/licenses/LICENSE-2.0
end_comment

begin_comment
comment|//
end_comment

begin_comment
comment|// Unless required by applicable law or agreed to in writing, software
end_comment

begin_comment
comment|// distributed under the License is distributed on an "AS IS" BASIS,
end_comment

begin_comment
comment|// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
end_comment

begin_comment
comment|// See the License for the specific language governing permissions and
end_comment

begin_comment
comment|// limitations under the License.
end_comment

begin_package
DECL|package|com.google.gerrit.server.config
package|package
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|server
operator|.
name|config
package|;
end_package

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|MoreObjects
operator|.
name|firstNonNull
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Strings
operator|.
name|emptyToNull
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Strings
operator|.
name|isNullOrEmpty
import|;
end_import

begin_import
import|import static
name|com
operator|.
name|google
operator|.
name|common
operator|.
name|base
operator|.
name|Strings
operator|.
name|nullToEmpty
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|common
operator|.
name|Nullable
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|common
operator|.
name|data
operator|.
name|GitwebType
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|common
operator|.
name|data
operator|.
name|ParameterizedString
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|common
operator|.
name|WebLinkInfo
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|registration
operator|.
name|DynamicSet
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|restapi
operator|.
name|Url
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|webui
operator|.
name|BranchWebLink
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|webui
operator|.
name|FileHistoryWebLink
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|webui
operator|.
name|FileWebLink
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|webui
operator|.
name|ParentWebLink
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|webui
operator|.
name|PatchSetWebLink
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|webui
operator|.
name|ProjectWebLink
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gerrit
operator|.
name|extensions
operator|.
name|webui
operator|.
name|TagWebLink
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|inject
operator|.
name|AbstractModule
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|inject
operator|.
name|Inject
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|inject
operator|.
name|Singleton
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jgit
operator|.
name|lib
operator|.
name|Config
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_class
DECL|class|GitwebConfig
specifier|public
class|class
name|GitwebConfig
block|{
DECL|field|log
specifier|private
specifier|static
specifier|final
name|Logger
name|log
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|GitwebConfig
operator|.
name|class
argument_list|)
decl_stmt|;
DECL|method|isDisabled (Config cfg)
specifier|public
specifier|static
name|boolean
name|isDisabled
parameter_list|(
name|Config
name|cfg
parameter_list|)
block|{
return|return
name|isEmptyString
argument_list|(
name|cfg
argument_list|,
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"url"
argument_list|)
operator|||
name|isEmptyString
argument_list|(
name|cfg
argument_list|,
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"cgi"
argument_list|)
operator|||
literal|"disabled"
operator|.
name|equals
argument_list|(
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"type"
argument_list|)
argument_list|)
return|;
block|}
DECL|class|LegacyModule
specifier|public
specifier|static
class|class
name|LegacyModule
extends|extends
name|AbstractModule
block|{
DECL|field|cfg
specifier|private
specifier|final
name|Config
name|cfg
decl_stmt|;
DECL|method|LegacyModule (Config cfg)
specifier|public
name|LegacyModule
parameter_list|(
name|Config
name|cfg
parameter_list|)
block|{
name|this
operator|.
name|cfg
operator|=
name|cfg
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|configure ()
specifier|protected
name|void
name|configure
parameter_list|()
block|{
name|GitwebType
name|type
init|=
name|typeFromConfig
argument_list|(
name|cfg
argument_list|)
decl_stmt|;
if|if
condition|(
name|type
operator|!=
literal|null
condition|)
block|{
name|bind
argument_list|(
name|GitwebType
operator|.
name|class
argument_list|)
operator|.
name|toInstance
argument_list|(
name|type
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|isNullOrEmpty
argument_list|(
name|type
operator|.
name|getBranch
argument_list|()
argument_list|)
condition|)
block|{
name|DynamicSet
operator|.
name|bind
argument_list|(
name|binder
argument_list|()
argument_list|,
name|BranchWebLink
operator|.
name|class
argument_list|)
operator|.
name|to
argument_list|(
name|GitwebLinks
operator|.
name|class
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|isNullOrEmpty
argument_list|(
name|type
operator|.
name|getTag
argument_list|()
argument_list|)
condition|)
block|{
name|DynamicSet
operator|.
name|bind
argument_list|(
name|binder
argument_list|()
argument_list|,
name|TagWebLink
operator|.
name|class
argument_list|)
operator|.
name|to
argument_list|(
name|GitwebLinks
operator|.
name|class
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|isNullOrEmpty
argument_list|(
name|type
operator|.
name|getFile
argument_list|()
argument_list|)
operator|||
operator|!
name|isNullOrEmpty
argument_list|(
name|type
operator|.
name|getRootTree
argument_list|()
argument_list|)
condition|)
block|{
name|DynamicSet
operator|.
name|bind
argument_list|(
name|binder
argument_list|()
argument_list|,
name|FileWebLink
operator|.
name|class
argument_list|)
operator|.
name|to
argument_list|(
name|GitwebLinks
operator|.
name|class
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|isNullOrEmpty
argument_list|(
name|type
operator|.
name|getFileHistory
argument_list|()
argument_list|)
condition|)
block|{
name|DynamicSet
operator|.
name|bind
argument_list|(
name|binder
argument_list|()
argument_list|,
name|FileHistoryWebLink
operator|.
name|class
argument_list|)
operator|.
name|to
argument_list|(
name|GitwebLinks
operator|.
name|class
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|isNullOrEmpty
argument_list|(
name|type
operator|.
name|getRevision
argument_list|()
argument_list|)
condition|)
block|{
name|DynamicSet
operator|.
name|bind
argument_list|(
name|binder
argument_list|()
argument_list|,
name|PatchSetWebLink
operator|.
name|class
argument_list|)
operator|.
name|to
argument_list|(
name|GitwebLinks
operator|.
name|class
argument_list|)
expr_stmt|;
name|DynamicSet
operator|.
name|bind
argument_list|(
name|binder
argument_list|()
argument_list|,
name|ParentWebLink
operator|.
name|class
argument_list|)
operator|.
name|to
argument_list|(
name|GitwebLinks
operator|.
name|class
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|isNullOrEmpty
argument_list|(
name|type
operator|.
name|getProject
argument_list|()
argument_list|)
condition|)
block|{
name|DynamicSet
operator|.
name|bind
argument_list|(
name|binder
argument_list|()
argument_list|,
name|ProjectWebLink
operator|.
name|class
argument_list|)
operator|.
name|to
argument_list|(
name|GitwebLinks
operator|.
name|class
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
DECL|method|isEmptyString (Config cfg, String section, String subsection, String name)
specifier|private
specifier|static
name|boolean
name|isEmptyString
parameter_list|(
name|Config
name|cfg
parameter_list|,
name|String
name|section
parameter_list|,
name|String
name|subsection
parameter_list|,
name|String
name|name
parameter_list|)
block|{
comment|// This is currently the only way to check for the empty string in a JGit
comment|// config. Fun!
name|String
index|[]
name|values
init|=
name|cfg
operator|.
name|getStringList
argument_list|(
name|section
argument_list|,
name|subsection
argument_list|,
name|name
argument_list|)
decl_stmt|;
return|return
name|values
operator|.
name|length
operator|>
literal|0
operator|&&
name|isNullOrEmpty
argument_list|(
name|values
index|[
literal|0
index|]
argument_list|)
return|;
block|}
DECL|method|typeFromConfig (Config cfg)
specifier|private
specifier|static
name|GitwebType
name|typeFromConfig
parameter_list|(
name|Config
name|cfg
parameter_list|)
block|{
name|GitwebType
name|defaultType
init|=
name|defaultType
argument_list|(
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"type"
argument_list|)
argument_list|)
decl_stmt|;
if|if
condition|(
name|defaultType
operator|==
literal|null
condition|)
block|{
return|return
literal|null
return|;
block|}
name|GitwebType
name|type
init|=
operator|new
name|GitwebType
argument_list|()
decl_stmt|;
name|type
operator|.
name|setLinkName
argument_list|(
name|firstNonNull
argument_list|(
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"linkname"
argument_list|)
argument_list|,
name|defaultType
operator|.
name|getLinkName
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|type
operator|.
name|setBranch
argument_list|(
name|firstNonNull
argument_list|(
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"branch"
argument_list|)
argument_list|,
name|defaultType
operator|.
name|getBranch
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|type
operator|.
name|setTag
argument_list|(
name|firstNonNull
argument_list|(
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"tag"
argument_list|)
argument_list|,
name|defaultType
operator|.
name|getTag
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|type
operator|.
name|setProject
argument_list|(
name|firstNonNull
argument_list|(
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"project"
argument_list|)
argument_list|,
name|defaultType
operator|.
name|getProject
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|type
operator|.
name|setRevision
argument_list|(
name|firstNonNull
argument_list|(
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"revision"
argument_list|)
argument_list|,
name|defaultType
operator|.
name|getRevision
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|type
operator|.
name|setRootTree
argument_list|(
name|firstNonNull
argument_list|(
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"roottree"
argument_list|)
argument_list|,
name|defaultType
operator|.
name|getRootTree
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|type
operator|.
name|setFile
argument_list|(
name|firstNonNull
argument_list|(
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"file"
argument_list|)
argument_list|,
name|defaultType
operator|.
name|getFile
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|type
operator|.
name|setFileHistory
argument_list|(
name|firstNonNull
argument_list|(
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"filehistory"
argument_list|)
argument_list|,
name|defaultType
operator|.
name|getFileHistory
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|type
operator|.
name|setUrlEncode
argument_list|(
name|cfg
operator|.
name|getBoolean
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"urlencode"
argument_list|,
name|defaultType
operator|.
name|getUrlEncode
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|String
name|pathSeparator
init|=
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"pathSeparator"
argument_list|)
decl_stmt|;
if|if
condition|(
name|pathSeparator
operator|!=
literal|null
condition|)
block|{
if|if
condition|(
name|pathSeparator
operator|.
name|length
argument_list|()
operator|==
literal|1
condition|)
block|{
name|char
name|c
init|=
name|pathSeparator
operator|.
name|charAt
argument_list|(
literal|0
argument_list|)
decl_stmt|;
if|if
condition|(
name|isValidPathSeparator
argument_list|(
name|c
argument_list|)
condition|)
block|{
name|type
operator|.
name|setPathSeparator
argument_list|(
name|firstNonNull
argument_list|(
name|c
argument_list|,
name|defaultType
operator|.
name|getPathSeparator
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|log
operator|.
name|warn
argument_list|(
literal|"Invalid gitweb.pathSeparator: "
operator|+
name|c
argument_list|)
expr_stmt|;
block|}
block|}
else|else
block|{
name|log
operator|.
name|warn
argument_list|(
literal|"gitweb.pathSeparator is not a single character: "
operator|+
name|pathSeparator
argument_list|)
expr_stmt|;
block|}
block|}
return|return
name|type
return|;
block|}
DECL|method|defaultType (String typeName)
specifier|private
specifier|static
name|GitwebType
name|defaultType
parameter_list|(
name|String
name|typeName
parameter_list|)
block|{
name|GitwebType
name|type
init|=
operator|new
name|GitwebType
argument_list|()
decl_stmt|;
switch|switch
condition|(
name|nullToEmpty
argument_list|(
name|typeName
argument_list|)
condition|)
block|{
case|case
literal|"gitweb"
case|:
name|type
operator|.
name|setLinkName
argument_list|(
literal|"gitweb"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setProject
argument_list|(
literal|"?p=${project}.git;a=summary"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setRevision
argument_list|(
literal|"?p=${project}.git;a=commit;h=${commit}"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setBranch
argument_list|(
literal|"?p=${project}.git;a=shortlog;h=${branch}"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setTag
argument_list|(
literal|"?p=${project}.git;a=tag;h=${tag}"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setRootTree
argument_list|(
literal|"?p=${project}.git;a=tree;hb=${commit}"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setFile
argument_list|(
literal|"?p=${project}.git;hb=${commit};f=${file}"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setFileHistory
argument_list|(
literal|"?p=${project}.git;a=history;hb=${branch};f=${file}"
argument_list|)
expr_stmt|;
break|break;
case|case
literal|"cgit"
case|:
name|type
operator|.
name|setLinkName
argument_list|(
literal|"cgit"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setProject
argument_list|(
literal|"${project}.git/summary"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setRevision
argument_list|(
literal|"${project}.git/commit/?id=${commit}"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setBranch
argument_list|(
literal|"${project}.git/log/?h=${branch}"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setTag
argument_list|(
literal|"${project}.git/tag/?h=${tag}"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setRootTree
argument_list|(
literal|"${project}.git/tree/?h=${commit}"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setFile
argument_list|(
literal|"${project}.git/tree/${file}?h=${commit}"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setFileHistory
argument_list|(
literal|"${project}.git/log/${file}?h=${branch}"
argument_list|)
expr_stmt|;
break|break;
case|case
literal|"custom"
case|:
comment|// For a custom type with no explicit link name, just reuse "gitweb".
name|type
operator|.
name|setLinkName
argument_list|(
literal|"gitweb"
argument_list|)
expr_stmt|;
name|type
operator|.
name|setProject
argument_list|(
literal|""
argument_list|)
expr_stmt|;
name|type
operator|.
name|setRevision
argument_list|(
literal|""
argument_list|)
expr_stmt|;
name|type
operator|.
name|setBranch
argument_list|(
literal|""
argument_list|)
expr_stmt|;
name|type
operator|.
name|setTag
argument_list|(
literal|""
argument_list|)
expr_stmt|;
name|type
operator|.
name|setRootTree
argument_list|(
literal|""
argument_list|)
expr_stmt|;
name|type
operator|.
name|setFile
argument_list|(
literal|""
argument_list|)
expr_stmt|;
name|type
operator|.
name|setFileHistory
argument_list|(
literal|""
argument_list|)
expr_stmt|;
break|break;
case|case
literal|""
case|:
case|case
literal|"disabled"
case|:
default|default:
return|return
literal|null
return|;
block|}
return|return
name|type
return|;
block|}
DECL|field|url
specifier|private
specifier|final
name|String
name|url
decl_stmt|;
DECL|field|type
specifier|private
specifier|final
name|GitwebType
name|type
decl_stmt|;
annotation|@
name|Inject
DECL|method|GitwebConfig (GitwebCgiConfig cgiConfig, @GerritServerConfig Config cfg)
name|GitwebConfig
parameter_list|(
name|GitwebCgiConfig
name|cgiConfig
parameter_list|,
annotation|@
name|GerritServerConfig
name|Config
name|cfg
parameter_list|)
block|{
if|if
condition|(
name|isDisabled
argument_list|(
name|cfg
argument_list|)
condition|)
block|{
name|type
operator|=
literal|null
expr_stmt|;
name|url
operator|=
literal|null
expr_stmt|;
block|}
else|else
block|{
name|String
name|cfgUrl
init|=
name|cfg
operator|.
name|getString
argument_list|(
literal|"gitweb"
argument_list|,
literal|null
argument_list|,
literal|"url"
argument_list|)
decl_stmt|;
name|type
operator|=
name|typeFromConfig
argument_list|(
name|cfg
argument_list|)
expr_stmt|;
if|if
condition|(
name|type
operator|==
literal|null
condition|)
block|{
name|url
operator|=
literal|null
expr_stmt|;
block|}
elseif|else
if|if
condition|(
name|cgiConfig
operator|.
name|getGitwebCgi
argument_list|()
operator|==
literal|null
condition|)
block|{
comment|// Use an externally managed gitweb instance, and not an internal one.
name|url
operator|=
name|cfgUrl
expr_stmt|;
block|}
else|else
block|{
name|url
operator|=
name|firstNonNull
argument_list|(
name|cfgUrl
argument_list|,
literal|"gitweb"
argument_list|)
expr_stmt|;
block|}
block|}
block|}
comment|/** @return GitwebType for gitweb viewer. */
annotation|@
name|Nullable
DECL|method|getGitwebType ()
specifier|public
name|GitwebType
name|getGitwebType
parameter_list|()
block|{
return|return
name|type
return|;
block|}
comment|/**    * @return URL of the entry point into gitweb. This URL may be relative to our context if gitweb    *     is hosted by ourselves; or absolute if its hosted elsewhere; or null if gitweb has not been    *     configured.    */
DECL|method|getUrl ()
specifier|public
name|String
name|getUrl
parameter_list|()
block|{
return|return
name|url
return|;
block|}
comment|/**    * Determines if a given character can be used unencoded in an URL as a replacement for the path    * separator '/'.    *    *<p>Reasoning: http://www.ietf.org/rfc/rfc1738.txt Â§ 2.2:    *    *<p>... only alphanumerics, the special characters "$-_.+!*'(),", and reserved characters used    * for their reserved purposes may be used unencoded within a URL.    *    *<p>The following characters might occur in file names, however:    *    *<p>alphanumeric characters,    *    *<p>"$-_.+!',"    */
DECL|method|isValidPathSeparator (char c)
specifier|static
name|boolean
name|isValidPathSeparator
parameter_list|(
name|char
name|c
parameter_list|)
block|{
switch|switch
condition|(
name|c
condition|)
block|{
case|case
literal|'*'
case|:
case|case
literal|'('
case|:
case|case
literal|')'
case|:
return|return
literal|true
return|;
default|default:
return|return
literal|false
return|;
block|}
block|}
annotation|@
name|Singleton
DECL|class|GitwebLinks
specifier|static
class|class
name|GitwebLinks
implements|implements
name|BranchWebLink
implements|,
name|FileHistoryWebLink
implements|,
name|FileWebLink
implements|,
name|PatchSetWebLink
implements|,
name|ParentWebLink
implements|,
name|ProjectWebLink
implements|,
name|TagWebLink
block|{
DECL|field|url
specifier|private
specifier|final
name|String
name|url
decl_stmt|;
DECL|field|type
specifier|private
specifier|final
name|GitwebType
name|type
decl_stmt|;
DECL|field|branch
specifier|private
specifier|final
name|ParameterizedString
name|branch
decl_stmt|;
DECL|field|file
specifier|private
specifier|final
name|ParameterizedString
name|file
decl_stmt|;
DECL|field|fileHistory
specifier|private
specifier|final
name|ParameterizedString
name|fileHistory
decl_stmt|;
DECL|field|project
specifier|private
specifier|final
name|ParameterizedString
name|project
decl_stmt|;
DECL|field|revision
specifier|private
specifier|final
name|ParameterizedString
name|revision
decl_stmt|;
DECL|field|tag
specifier|private
specifier|final
name|ParameterizedString
name|tag
decl_stmt|;
annotation|@
name|Inject
DECL|method|GitwebLinks (GitwebConfig config, GitwebType type)
name|GitwebLinks
parameter_list|(
name|GitwebConfig
name|config
parameter_list|,
name|GitwebType
name|type
parameter_list|)
block|{
name|this
operator|.
name|url
operator|=
name|config
operator|.
name|getUrl
argument_list|()
expr_stmt|;
name|this
operator|.
name|type
operator|=
name|type
expr_stmt|;
name|this
operator|.
name|branch
operator|=
name|parse
argument_list|(
name|type
operator|.
name|getBranch
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|file
operator|=
name|parse
argument_list|(
name|firstNonNull
argument_list|(
name|emptyToNull
argument_list|(
name|type
operator|.
name|getFile
argument_list|()
argument_list|)
argument_list|,
name|nullToEmpty
argument_list|(
name|type
operator|.
name|getRootTree
argument_list|()
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|this
operator|.
name|fileHistory
operator|=
name|parse
argument_list|(
name|type
operator|.
name|getFileHistory
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|project
operator|=
name|parse
argument_list|(
name|type
operator|.
name|getProject
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|revision
operator|=
name|parse
argument_list|(
name|type
operator|.
name|getRevision
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|tag
operator|=
name|parse
argument_list|(
name|type
operator|.
name|getTag
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
DECL|method|getBranchWebLink (String projectName, String branchName)
specifier|public
name|WebLinkInfo
name|getBranchWebLink
parameter_list|(
name|String
name|projectName
parameter_list|,
name|String
name|branchName
parameter_list|)
block|{
if|if
condition|(
name|branch
operator|!=
literal|null
condition|)
block|{
return|return
name|link
argument_list|(
name|branch
operator|.
name|replace
argument_list|(
literal|"project"
argument_list|,
name|encode
argument_list|(
name|projectName
argument_list|)
argument_list|)
operator|.
name|replace
argument_list|(
literal|"branch"
argument_list|,
name|encode
argument_list|(
name|branchName
argument_list|)
argument_list|)
operator|.
name|toString
argument_list|()
argument_list|)
return|;
block|}
return|return
literal|null
return|;
block|}
annotation|@
name|Override
DECL|method|getTagWebLink (String projectName, String tagName)
specifier|public
name|WebLinkInfo
name|getTagWebLink
parameter_list|(
name|String
name|projectName
parameter_list|,
name|String
name|tagName
parameter_list|)
block|{
if|if
condition|(
name|tag
operator|!=
literal|null
condition|)
block|{
return|return
name|link
argument_list|(
name|tag
operator|.
name|replace
argument_list|(
literal|"project"
argument_list|,
name|encode
argument_list|(
name|projectName
argument_list|)
argument_list|)
operator|.
name|replace
argument_list|(
literal|"tag"
argument_list|,
name|encode
argument_list|(
name|tagName
argument_list|)
argument_list|)
operator|.
name|toString
argument_list|()
argument_list|)
return|;
block|}
return|return
literal|null
return|;
block|}
annotation|@
name|Override
DECL|method|getFileHistoryWebLink (String projectName, String revision, String fileName)
specifier|public
name|WebLinkInfo
name|getFileHistoryWebLink
parameter_list|(
name|String
name|projectName
parameter_list|,
name|String
name|revision
parameter_list|,
name|String
name|fileName
parameter_list|)
block|{
if|if
condition|(
name|fileHistory
operator|!=
literal|null
condition|)
block|{
return|return
name|link
argument_list|(
name|fileHistory
operator|.
name|replace
argument_list|(
literal|"project"
argument_list|,
name|encode
argument_list|(
name|projectName
argument_list|)
argument_list|)
operator|.
name|replace
argument_list|(
literal|"branch"
argument_list|,
name|encode
argument_list|(
name|revision
argument_list|)
argument_list|)
operator|.
name|replace
argument_list|(
literal|"file"
argument_list|,
name|encode
argument_list|(
name|fileName
argument_list|)
argument_list|)
operator|.
name|toString
argument_list|()
argument_list|)
return|;
block|}
return|return
literal|null
return|;
block|}
annotation|@
name|Override
DECL|method|getFileWebLink (String projectName, String revision, String fileName)
specifier|public
name|WebLinkInfo
name|getFileWebLink
parameter_list|(
name|String
name|projectName
parameter_list|,
name|String
name|revision
parameter_list|,
name|String
name|fileName
parameter_list|)
block|{
if|if
condition|(
name|file
operator|!=
literal|null
condition|)
block|{
return|return
name|link
argument_list|(
name|file
operator|.
name|replace
argument_list|(
literal|"project"
argument_list|,
name|encode
argument_list|(
name|projectName
argument_list|)
argument_list|)
operator|.
name|replace
argument_list|(
literal|"commit"
argument_list|,
name|encode
argument_list|(
name|revision
argument_list|)
argument_list|)
operator|.
name|replace
argument_list|(
literal|"file"
argument_list|,
name|encode
argument_list|(
name|fileName
argument_list|)
argument_list|)
operator|.
name|toString
argument_list|()
argument_list|)
return|;
block|}
return|return
literal|null
return|;
block|}
annotation|@
name|Override
DECL|method|getPatchSetWebLink (String projectName, String commit)
specifier|public
name|WebLinkInfo
name|getPatchSetWebLink
parameter_list|(
name|String
name|projectName
parameter_list|,
name|String
name|commit
parameter_list|)
block|{
if|if
condition|(
name|revision
operator|!=
literal|null
condition|)
block|{
return|return
name|link
argument_list|(
name|revision
operator|.
name|replace
argument_list|(
literal|"project"
argument_list|,
name|encode
argument_list|(
name|projectName
argument_list|)
argument_list|)
operator|.
name|replace
argument_list|(
literal|"commit"
argument_list|,
name|encode
argument_list|(
name|commit
argument_list|)
argument_list|)
operator|.
name|toString
argument_list|()
argument_list|)
return|;
block|}
return|return
literal|null
return|;
block|}
annotation|@
name|Override
DECL|method|getParentWebLink (String projectName, String commit)
specifier|public
name|WebLinkInfo
name|getParentWebLink
parameter_list|(
name|String
name|projectName
parameter_list|,
name|String
name|commit
parameter_list|)
block|{
comment|// For Gitweb treat parent revision links the same as patch set links
return|return
name|getPatchSetWebLink
argument_list|(
name|projectName
argument_list|,
name|commit
argument_list|)
return|;
block|}
annotation|@
name|Override
DECL|method|getProjectWeblink (String projectName)
specifier|public
name|WebLinkInfo
name|getProjectWeblink
parameter_list|(
name|String
name|projectName
parameter_list|)
block|{
if|if
condition|(
name|project
operator|!=
literal|null
condition|)
block|{
return|return
name|link
argument_list|(
name|project
operator|.
name|replace
argument_list|(
literal|"project"
argument_list|,
name|encode
argument_list|(
name|projectName
argument_list|)
argument_list|)
operator|.
name|toString
argument_list|()
argument_list|)
return|;
block|}
return|return
literal|null
return|;
block|}
DECL|method|encode (String val)
specifier|private
name|String
name|encode
parameter_list|(
name|String
name|val
parameter_list|)
block|{
if|if
condition|(
name|type
operator|.
name|getUrlEncode
argument_list|()
condition|)
block|{
return|return
name|Url
operator|.
name|encode
argument_list|(
name|type
operator|.
name|replacePathSeparator
argument_list|(
name|val
argument_list|)
argument_list|)
return|;
block|}
return|return
name|val
return|;
block|}
DECL|method|link (String rest)
specifier|private
name|WebLinkInfo
name|link
parameter_list|(
name|String
name|rest
parameter_list|)
block|{
return|return
operator|new
name|WebLinkInfo
argument_list|(
name|type
operator|.
name|getLinkName
argument_list|()
argument_list|,
literal|null
argument_list|,
name|url
operator|+
name|rest
argument_list|,
literal|null
argument_list|)
return|;
block|}
DECL|method|parse (String pattern)
specifier|private
specifier|static
name|ParameterizedString
name|parse
parameter_list|(
name|String
name|pattern
parameter_list|)
block|{
if|if
condition|(
operator|!
name|isNullOrEmpty
argument_list|(
name|pattern
argument_list|)
condition|)
block|{
return|return
operator|new
name|ParameterizedString
argument_list|(
name|pattern
argument_list|)
return|;
block|}
return|return
literal|null
return|;
block|}
block|}
block|}
end_class

end_unit

